### ISSUE TITLE
PSSH library

### ISSUE THREAD

**Issue by white-line** [ClusterLabs/crmsh#100]
crm(live)# cluster init
ERROR: cluster.init: PSSH library is not installed or is not up to date.

crmsh-2.1.0, compiled on debian jessie (8.1)

**Comment by krig** [comment]
The cluster init (cluster scripts) feature requires either a patched pssh library, or, if the version is new enough, the python parallax package to be installed.

If you upgrade to the latest version of crmsh, you can install the necessary python package using pip:

    pip install parallax
