### ISSUE TITLE
'crm node list' doesn't show remote nodes

### ISSUE THREAD

**Issue by aspiers** [ClusterLabs/crmsh#103]
`crm node list` doesn't list remote nodes, because that code path does not invoke [the `listnodes()` function](https://github.com/ClusterLabs/crmsh/blob/master/modules/xmlutil.py#L338); instead [it simply calls `cib_elem.xpath("//configuration/nodes")[0]` itself and then iterates over the result of that](https://github.com/ClusterLabs/crmsh/blob/master/modules/ui_node.py#L131).

**Comment by krig** [comment]
Ah, good catch!
