### ISSUE TITLE
crm status command error

### ISSUE THREAD

**Issue by mashiguo** [ClusterLabs/crmsh#1042]
error: Could not connect to launcher: Connection refused
crm_mon: Connection to cluster failed: Connection refused
ERROR: status: crm_mon (rc=102): 
error: Could not connect to the CIB manager: Transport endpoint is not con>

pacemaker logs:
tail -f  /var/log/pacemaker/pacemaker.log
Oct 28 13:46:55 node-2 pacemakerd          [12941] (crm_log_init) 	info: Changed active directory to /var/lib/pacemaker/cores
Oct 28 13:46:55 node-2 pacemakerd          [12941] (ipc_post_disconnect) 	info: Disconnected from launcher IPC API
Oct 28 13:46:55 node-2 pacemakerd          [12941] (mcp_read_config) 	info: Could not connect to Corosync CMAP: CS_ERR_LIBRARY (retrying in 1s) | rc=2
Oct 28 13:46:56 node-2 pacemakerd          [12941] (mcp_read_config) 	info: Could not connect to Corosync CMAP: CS_ERR_LIBRARY (retrying in 2s) | rc=2
Oct 28 13:46:58 node-2 pacemakerd          [12941] (mcp_read_config) 	info: Could not connect to Corosync CMAP: CS_ERR_LIBRARY (retrying in 3s) | rc=2
Oct 28 13:47:01 node-2 pacemakerd          [12941] (mcp_read_config) 	info: Could not connect to Corosync CMAP: CS_ERR_LIBRARY (retrying in 4s) | rc=2
Oct 28 13:47:05 node-2 pacemakerd          [12941] (mcp_read_config) 	info: Could not connect to Corosync CMAP: CS_ERR_LIBRARY (retrying in 5s) | rc=2
Oct 28 13:47:10 node-2 pacemakerd          [12941] (mcp_read_config) 	crit: Could not connect to Corosync CMAP: CS_ERR_LIBRARY | rc=2
Oct 28 13:47:10 node-2 pacemakerd          [12941] (crm_exit) 	info: Exiting pacemakerd | with status 69

**Comment by liangxin1300** [comment]
Is the cluster service started successfully?

And which version of pacemaker, corosync and crmsh are you using?
