### ISSUE TITLE
can't crm configure edit remote resource

### ISSUE THREAD

**Issue by aspiers** [ClusterLabs/crmsh#109]
Seems to be due to the node / resource id clash:

http://pastebin.suse.de/16082

**Comment by krig** [comment]
Should be fixed by https://github.com/ClusterLabs/crmsh/commit/14fa72bb8b51448f381d9aa037a5780085f16c1a

Please help me verify :)

**Comment by aspiers** [comment]
Unfortunately that doesn't apply to crmsh-2.2.0~rc3+git.1443105613.80a246f-1.1.noarch :-(

**Comment by krig** [comment]
Oh yeah, you need all the other fixes for node/resource id collision as well. But you should be able to grab an .rpm you can use from `network:ha-clustering:Factory`.

**Comment by aspiers** [comment]
I branched from `network:ha-clustering:Factory`, updated to latest git `master`, built, installed, and tested - it works!  Thanks!
