### ISSUE TITLE
Centos7 repository missing

### ISSUE THREAD

**Issue by Aegil** [ClusterLabs/crmsh#1196]
Hey,
it seems at some point in the last 2 weeks the centos7 repos have disappeared. 

http://download.opensuse.org/repositories/network:/ha-clustering:/Stable/CentOS_CentOS-7/network:ha-clustering:Stable.repo

Is it possible to get those back or is there an archive some place available?

Thanks

**Comment by liangxin1300** [comment]
Add it back

Thanks!
