### ISSUE TITLE
bootstrap join consumes unnecessary time on passwordless checks for the existing cluster

### ISSUE THREAD

**Issue by zzhou1** [ClusterLabs/crmsh#1239]
Could bootstrap join skips "Checking passwordless" among the existing 3-node cluster, when the 4th new node joins the cluster? It's noticeable time consuming when the cluster is large, and is not a good enough user experience. Example as below,

```
hanode4: # crm cluster join -yc hanode1                                        
[...]
INFO: Checking passwordless for hacluster between hanode1 and hanode2
INFO: Checking passwordless for hacluster between hanode1 and hanode3
INFO: Checking passwordless for hacluster between hanode2 and hanode1
INFO: Checking passwordless for hacluster between hanode2 and hanode3
INFO: Checking passwordless for hacluster between hanode3 and hanode1
INFO: Checking passwordless for hacluster between hanode3 and hanode2
[...]
```

**Comment by nicholasyang2022** [comment]
I think it is a workaround for certain use case related to `-N` option used in bootstrap, which does not swap public keys correctly. I will try to find the root cause.
