### ISSUE TITLE
[Question] The use of stash becomes the error.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/crmsh#124]
Hi All,

I fail when I carry out stash in the environment that put Pacemaker1.1.14 and crmsh2.1.5 together.
(and pssh 2.3.1(pssh-2.3.1-5.el7.noarch.rpm))

Step 1)  Start a cluster in 2 nodes.
```
[root@rh72-01 ~]# crm_mon -1 -Af
Last updated: Tue Mar 22 10:10:51 2016          Last change: Tue Mar 22 10:10:45 2016 by root via cibadmin on rh72-01
Stack: corosync
Current DC: rh72-02 (version 1.1.14-70404b0) - partition with quorum
2 nodes and 2 resources configured

Online: [ rh72-01 rh72-02 ]

 prmStonith1-2  (stonith:external/ssh): Started rh72-01
 prmStonith2-2  (stonith:external/ssh): Started rh72-02

Node Attributes:
* Node rh72-01:
* Node rh72-02:

Migration Summary:
* Node rh72-02:
* Node rh72-01:
```

Step 2) Carry out stash, but an option of pssh fails by injustice

```
[root@rh72-01 ~]# crm resource secret prmStonith1-2 stash hostlist
INFO: syncing /var/lib/heartbeat/lrm/secrets/prmStonith1-2/hostlist to rh72-02 ...
Usage: pssh [OPTIONS] command [...]

pssh: error: no such option: -q

```

However, the practice of stash succeeds when I compose a cluster of a single node.

In crmsh2.2.x, it seems to be switched from pssh to the use of parallax.

In crmsh2.1.5, can the user not carry out stash in plural nodes?
Is the practice of stash possible by some kind of setting?

Best Regards,
Hideo Yamauchi.

**Comment by krig** [comment]
Hello,

The `-q` flag for pssh is added via a patch to pssh, which has been proposed upstream but unfortunately the pssh project seems to be abandoned :( This is the reason for switching from pssh to parallax.

To get the `-q` parameter, you would either need to use the pssh package which is already patched from the OBS:

https://software.opensuse.org/download.html?project=network%3Aha-clustering%3AFactory&package=pssh

or, alternatively, patch pssh yourself. You can find the relevant patches here:

https://build.opensuse.org/package/show/network:ha-clustering:Factory/pssh

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Thank you for comment.
I try it in pssh of the patch.

Many Thanks!
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

pssh where a summary made a patch seems to move well.

Do you make rpm for the distribution of other linux?
If there is rpm of this pssh for RHEL7/RHEL6, we intend to use it.

Best Regards,
Hideo Yamauchi.

**Comment by krig** [comment]
Hi, there are RPMs available here:

https://software.opensuse.org/download.html?project=network%3Aha-clustering%3AStable&package=pssh

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Great!

Many thanks!
Hideo Yamauchi.

**Comment by krig** [comment]
Hello Hideo-san,

No problem! Let me know if there are any problems with the rpm packages.

Thank you,
Kristoffer

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

All right!

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Let me ask you a question because I do not know a lot about python.
The site-package is not included in rpm which you showed.


[root@rh72-01 opt]# rpm -qpl pssh-2.3.1-4.1.x86_64.rpm 
warning: pssh-2.3.1-4.1.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID 17280ddf: NOKEY
/usr/bin/pnuke
/usr/bin/prsync
/usr/bin/pscp
/usr/bin/pslurp
/usr/bin/pssh
/usr/bin/pssh-askpass
/usr/share/doc/pssh-2.3.1
/usr/share/doc/pssh-2.3.1/AUTHORS
/usr/share/doc/pssh-2.3.1/COPYING
/usr/share/doc/pssh-2.3.1/ChangeLog
/usr/share/man/man1/pnuke.1.gz
/usr/share/man/man1/prsync.1.gz
/usr/share/man/man1/pscp.1.gz
/usr/share/man/man1/pslurp.1.gz
/usr/share/man/man1/pssh.1.gz

site-package does not seem to be included in rpm of SUSE either.

Is site-package different rpm?

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Sorry....I found it!

https://software.opensuse.org/download.html?project=network%3Aha-clustering%3AStable&package=python-pssh

Many Thanks,
Hideo Yamauchi.
