### ISSUE TITLE
crmsh - cluster health gives error when using FQDN

### ISSUE THREAD

**Issue by vanandel** [ClusterLabs/crmsh#128]
/usr/share/crmsh/scripts/health/collect.py 
has a function sys_info()

sys_info() has the following statement which returns the host portion of a FQDN.
hostname = platform.node().split('.')[0]

This results in the error message:
ERROR: Hostname mismatch: control1.gate.rtf is not control1

If sys_info() simply uses the statement:
hostname = platform.node()

"crm  cluster health" 
doesn't produce the bogus error message.

**Comment by krig** [comment]
I think this may be due to a difference between platforms in how they handle hostnames and FQDN.
Possibly related issue: https://bugzilla.novell.com/show_bug.cgi?id=820213

May I ask which distribution you are running?

**Comment by vanandel** [comment]
I'm using CentOS 7.2

**Comment by krig** [comment]
Note to myself: switch to reading `os.uname()[1]`, that's what crmsh itself uses.

**Comment by krig** [comment]
Please help verify that commit 4bec710 really does fix this for you. Thanks!
