### ISSUE TITLE
There is no interface available to remove the properties that have been added

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#1298]
Have to use `crm_attribute` like `crm_attribute --delete -t crm_config --name stonith-enabled`, which is not convenient

**Comment by liangxin1300** [comment]
Two solutions:

1. Reuse crm->configure->delete, now the `delete` command can only delete the whole block of section, given the section id, such as `build-resource-defaults`, `cib-bootstrap-options`, node id and resource id
2. Add crm->configure->delete_property, it seems reasonable since we already have `property` and `get_property`

In anyways, crmsh will call `crm_attribute --type <section_type> --name <property_name> --delete` command;
Since the valid values of `--type` are: crm_config, rsc_defaults, op_defaults, tickets, we can also delete resource and operation default options

What do you think?

@zzhou1 @nicholasyang2022 @gao-yan

**Comment by nicholasyang2022** [comment]
Do we really need a subcommand, which just mirrors the same behavior of `crm_attribute --delete`? I think crmsh is expected to provide more abstract and higher level interfaces than pacemaker command line utils.

**Comment by liangxin1300** [comment]
Already added `utils.delete_property` in #1479
