### ISSUE TITLE
[UX] bundle: embrace the multiline format and ensure the integrity of the bundle primitive view

### ISSUE THREAD

**Issue by zzhou1** [ClusterLabs/crmsh#1303]
REF: https://clusterlabs.org/pacemaker/doc/2.1/Pacemaker_Explained/singlehtml/index.html#bundle-container-properties

1. Here is the current `crmsh configure show`. 

  ```
  bundle nfsserver1 \
          docker image=nfsserver options="--privileged --stop-signal SIGRTMIN+3" run-command="/usr/lib/systemd/systemd --system --unit=run_pcmk_remote_and_nfs_server.target" \
          network ip-range-start=192.168.1.200 port-mapping id=nfs1_port_sunrpc port=111 port-mapping id=nfs1_port_data port=2049 port-mapping id=nfs1_port_rpcmount port=20048 port-mapping id=nfs1_port_statd port=662 port-mapping id=nfs1_port_lockd-tcpudp port=32768 \
          storage storage-mapping id=nfs1-state source-dir="/srv/nfs1/state" target-dir="/var/lib/nfs" options=rw storage-mapping id=nfs1-share source-dir="/srv/nfs1/share" target-dir="/srv/nfs/share" options=rw \
```

  Those lines are too long. It is much more readable to break lines, for example, 

  ```
  bundle nfsserver1 \
          docker image=nfsserver \
              options="--privileged --stop-signal SIGRTMIN+3" \
              run-command="/usr/lib/systemd/systemd --system --unit=run_pcmk_remote_and_nfs_server.target" \
          network ip-range-start=192.168.1.200 \
                port-mapping id=nfs1_port_sunrpc port=111 \
                port-mapping id=nfs1_port_data port=2049 \
                port-mapping id=nfs1_port_rpcmount port=20048 \
                port-mapping id=nfs1_port_statd port=662 \
                port-mapping id=nfs1_port_lockd-tcpudp port=32768 \
          storage storage-mapping id=nfs1-state source-dir="/srv/nfs1/state" target-dir="/var/lib/nfs" options=rw \
                storage-mapping id=nfs1-share source-dir="/srv/nfs1/share" target-dir="/srv/nfs/share" options=rw \
  ```

2. Also the current layout is strange as below. That could break the integrity and make the wrong logic for the onliner cli to start the normal primitive outside the bundle resource. 

  primitive exportfs1 exportfs \
      params directory="/srv/nfs/share" options="rw,mountpoint" clientspec="*" \
      op monitor interval=30s timeout=40s \
      op start timeout=60s interval=0s \
      op stop timeout=120s interval=0s

  bundle nfsserver1 \
          primitive exportfs1

  The nature view is just to make the bundle primitive inside its owner bundle resource, for example.

  bundle nfsserver1 \
      primitive exportfs1 exportfs \
        params directory="/srv/nfs/share" options="rw,mountpoint" clientspec="*" \
        op monitor interval=30s timeout=40s \
        op start timeout=60s interval=0s \
        op stop timeout=120s interval=0s

**Comment by liangxin1300** [comment]
For the second
> Also the current layout is strange as below. That could break the integrity and make the wrong logic for the onliner cli to start the normal primitive outside the bundle resource.

This is the group case
```
primitive dummy1 Dummy \
	meta target-role=Stopped \
	op monitor interval=10s timeout=20s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
primitive dummy2 Dummy \
	meta target-role=Stopped \
	op monitor interval=10s timeout=20s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
primitive dummy3 Dummy \
	meta target-role=Stopped \
	op monitor interval=10s timeout=20s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
primitive dummy4 Dummy \
	meta target-role=Stopped \
	op monitor interval=10s timeout=20s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
group g1 dummy1 dummy2
group g2 dummy3 dummy4
```

I think the current above layout is fine



```
bundle nfsserver1
primitive exportfs1 exportfs
params directory="/srv/nfs/share" options="rw,mountpoint" clientspec="*"
op monitor interval=30s timeout=40s
op start timeout=60s interval=0s
op stop timeout=120s interval=0s
````

This might make mess with bundle's options and network/storage options
