### ISSUE TITLE
Is "cibadmin_opt" a typo of "cibadm_opt" at line 414 in crmsh/log.py?

### ISSUE THREAD

**Issue by pangle-zhang** [ClusterLabs/crmsh#1306]
https://github.com/ClusterLabs/crmsh/blame/d797e0447ef01d2326d0d4a33ca21579153a5f35/crmsh/log.py#L414

    def update_err(self, obj_id, cibadm_opt, xml, rc):    <<<<<<<<< parameter "cibadm_opt"
        CIB_PERMISSION_DENIED_CODE = 54
        task_table = {"-U": "update", "-D": "delete", "-P": "patch"}
        task = task_table.get(cibadmin_opt, "replace")        <<<<<<<<< is "cibadmin_opt" a typo of "cibadm_opt"?
        self.logger.error("could not %s %s (rc=%d)", task, obj_id, int(rc))
        if int(rc) == CIB_PERMISSION_DENIED_CODE:
            self.logger.info("Permission denied.")
        elif task == "patch":
            self.logger.info("offending xml diff: %s", xml)
        else:
            self.logger.info("offending xml: %s", xml)

**Comment by liangxin1300** [comment]
Yeah, it should be

Fixed in #1308 
Thanks!
