### ISSUE TITLE
crm status failing to work after adding remote node

### ISSUE THREAD

**Issue by MoizArif** [ClusterLabs/crmsh#131]
Here is what this problem is:
1. output of crm status:
`Last updated: Mon Apr 11 09:29:19 2016
Last change: Mon Apr 11 09:17:35 2016 via cibadmin on juju-machine-2-lxc-20
Stack: corosync
Current DC: juju-machine-2-lxc-20 (1006) - partition with quorum
Version: 1.1.10-42f2063
3 Nodes configured
8 Resources configured

Online: [ juju-machine-1-lxc-20 juju-machine-2-lxc-20 juju-machine-8-lxc-20 ]

 Clone Set: cl_ping [ping]
     Started: [ juju-machine-1-lxc-20 juju-machine-2-lxc-20 juju-machine-8-lxc-20 ]
 res_nova_consoleauth   (ocf::openstack:nova-consoleauth):      Started juju-machine-8-lxc-20
 Resource Group: grp_nova_vips
     res_nova_eth0_vip  (ocf::heartbeat:IPaddr2):       Started juju-machine-8-lxc-20
 Clone Set: cl_nova_haproxy [res_nova_haproxy]
     Started: [ juju-machine-1-lxc-20 juju-machine-2-lxc-20 juju-machine-8-lxc-20 ]`

2. Adding a remote node:
`crm configure primitive compute0-B3 ocf:pacemaker:remote op monitor interval=20`

3. crm status:
`Segmentation fault (core dumped)
ERROR: crm_mon exited with code 139 and said:`

4. crm_mon:
`Last updated: Mon Apr 11 10:54:59 2016
Last change: Mon Apr 11 10:32:05 2016 via cibadmin on juju-machine-2-lxc-20
Stack: corosync
Current DC: juju-machine-2-lxc-20 (1006) - partition with quorum
Version: 1.1.10-42f2063
6 Nodes configured
17 Resources configured

Segmentation fault (core dumped)`

------------
My setup:

1. Ubuntu 14.04.4 LTS
2. Kilo Release (2015.1.3)
3. pacemaker: 1.1.10+git20130802-1ubuntu2.3
4. pacemaker-cli-utils: 1.1.10+git20130802-1ubuntu2.3
5. corosync: 2.3.3-1ubuntu2
6. libcorosync-common4: 2.3.3-1ubuntu2
7. resource agents: 1:3.9.3+git20121009-3ubuntu2
8. pacemaker-remote: 1.1.10+git20130802-1ubuntu2.3
9. fence-agents: 3.1.5-2ubuntu4

**Comment by dmuhamedagic** [comment]
> `Segmentation fault (core dumped)
> ERROR: crm_mon exited with code 139 and said:`

This is a bug in crm_mon which is part of pacemaker.

> 3. pacemaker: 1.1.10+git20130802-1ubuntu2.3

This is an oldish version, so best to open an issue with ubuntu.

**Comment by MoizArif** [comment]
bug on launchpad ?

**Comment by krig** [comment]
Closing since it's a bug in pacemaker.
