### ISSUE TITLE
crmsh parser fails to parse cli arguments with op monitor role given

### ISSUE THREAD

**Issue by dhoffend** [ClusterLabs/crmsh#1314]
This issue looks to be related the the ocf 1.1 schema upgrade/"validate-with" >= pacemaker-3.7 On Debian 11 systems (with crmsh 4.0/pacemaker 2.0) it works, on Debian 12 (with crmsh 4.4/pacemaker 2.1) it fails.

From the looks it looks like it trys to detect the schema, but a fresh initialized cib object doesn't know which schema it is to support yet. This only affects the " op monitor role=" parameter. It doesn't matter wether the old "master/slave" or the newer "promoted/unpromoted" roles are used. The validate-with key isn't set yet, therefore the check fails.

From looking at the current code there's no major change on the problematic parts:
* https://github.com/ClusterLabs/crmsh/blob/master/crmsh/cibconfig.py#L2471
* https://github.com/ClusterLabs/crmsh/blob/master/crmsh/utils.py#L3285

I guess when no schema/"validate-with" is provided the default of the current pacemaker version should be used. But i might be wrong. 

Also I didn't found any unit tests exactly for this op monitor role issue I came across
* https://github.com/ClusterLabs/crmsh/blob/master/test/unittests/test_parse.py#L158

Testcode on Debian 12:

```
import crmsh.parse
cmd = "primitive db ocf:heartbeat:mariadb " \ 
    "op monitor interval=29 role=Promoted " \ 
    "op monitor interval=31 role=Unpromoted " 
clip = crmsh.parse 
cib = clip.parse(cmd)
```

Excecption:

```
# python3 test.py 
Traceback (most recent call last):
  File "/root/test.py", line 6, in <module>
    cib = clip.parse(cmd)
          ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/crmsh/parse.py", line 1752, in parse
    ret = parser.do_parse(s, ignore_empty)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/crmsh/parse.py", line 178, in do_parse
    out = self.parse(cmd)
          ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/crmsh/parse.py", line 807, in parse
    return self.begin_dispatch(cmd, min_args=2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/crmsh/parse.py", line 170, in begin_dispatch
    return self.match_dispatch(errmsg="Unknown command")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/crmsh/parse.py", line 391, in match_dispatch
    return getattr(self, t)()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/crmsh/parse.py", line 833, in _primitive_or_template
    self.match_arguments(out, {'params': 'instance_attributes',
  File "/usr/lib/python3/dist-packages/crmsh/parse.py", line 639, in match_arguments
    self.match_operations(out, t == 'operations')
  File "/usr/lib/python3/dist-packages/crmsh/parse.py", line 744, in match_operations
    self.match_op(node, pfx=pfx)
  File "/usr/lib/python3/dist-packages/crmsh/parse.py", line 698, in match_op
    all_attrs = self.match_nvpairs(minpairs=0)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/crmsh/parse.py", line 309, in match_nvpairs
    ret.append(xmlutil.nvpair(self.matched(1),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/crmsh/xmlutil.py", line 1430, in nvpair
    value = handle_role_for_ocf_1_1(value, name=name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/crmsh/utils.py", line 3064, in handle_role_for_ocf_1_1
    if value in downgrade_dict and not is_ocf_1_1_cib_schema_detected():
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/crmsh/utils.py", line 3050, in is_ocf_1_1_cib_schema_detected
    return is_larger_than_min_version(cib_factory.get_schema(), constants.SCHEMA_MIN_VER_SUPPORT_OCF_1_1)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/crmsh/cibconfig.py", line 2438, in get_schema
    return self.cib_attrs["validate-with"]
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'validate-with'

```

**Comment by nicholasyang2022** [comment]
Yeah, we can use `pacemakerd --version` instead when cib is not available.

**Comment by dhoffend** [comment]
```
root@ha01:~# pacemakerd --version
Pacemaker 2.1.5
```
sadly this won't represent the schema name (like pacemaker-3.x) But it might be a start

**Comment by dhoffend** [comment]
Maybe this helps

```
root@ha01:~# find /usr/share/pacemaker/ -type f -name "pacemaker-[0-9].*rng" -exec sh -c 'echo "$(basename {} .rng)"' \; | sort -V | tail -n1
pacemaker-3.9
```

I guess there's already a piece of code somewhere that reads those rng schema files. Hopyfully the newest version (not the -next version) is the one we're searching for

**Comment by nicholasyang2022** [comment]
> sadly this won't represent the schema name (like pacemaker-3.x)

Yes, they are not the same. `3.9` is corresponding to [CRM feature set](http://web.archive.org/web/20220521081621/https://wiki.clusterlabs.org/wiki/Pacemaker_feature_set). The latest feature set supported by pacemaker can be queried from `pacemakerd -F`. And from the [pacemake ChangeLog](https://github.com/ClusterLabs/pacemaker/blob/main/ChangeLog) we know that ocf 1.1 support was added in release version 2.1.

I'd like to keep it simple, so I prefer to use the release version.

@liangxin1300 What's your opinion?

**Comment by liangxin1300** [comment]
@dhoffend What's your output of this command?
```
crm(live/15sp5-1)configure# schema
pacemaker-3.9
crm(live/15sp5-1)configure# schema pacemaker-3.9
INFO: already using schema pacemaker-3.9
```

**Comment by liangxin1300** [comment]
Hi @dhoffend 
Two questions:
1. I wonder why there is no `validate-with` in cib? Did you removed it manually? Since that's one of first a few attributes that set for a fresh cib
2. The function `get_schema` was introduced in 2012, was very old, and did exist in 4.0.0, I wonder why it works without raising `KeyError`? What's your output of command `crm configure schema` with crmsh 4.0/pacemaker 2.0?

**Comment by dhoffend** [comment]
@liangxin1300 My output is correct

```
root@cmp-ha02:~# crm conf
crm(live/cmp-ha02)configure# schema
pacemaker-3.9
```

But that's not the point.

1. I've not removed the `validate-with` attribute. That's why I showed you the minimalistic python example. The real reason behind my question: I'm using a patched version of pacemaker module for ansible which uses the crmsh python lib to validate the commands given using the CliParser version. https://github.com/yosshy/ansible-pacemaker/blob/master/pacemaker#L89-L93
2.  I've seen that the `get_schema` function exists for quite some time, and I guess it will work fine when using with a given cib. But when just calling the CliParser without initializing a cib before it won't know the schema to validate against.

My guess is: With the introduction of the ocf_1_1 detection, there might be an edge-case where `get_schema` fails to return something when the cib object has just been created using the cibfactory and not loaded any structure yet.

The other cliparser checks work fine, because there's not ocf_1_1 translation which tries to check if the role name must be translated.

**Comment by dhoffend** [comment]
Just to have a clean check: I've added my example command to the unit test_parse section and it failed as well. So it's nothing that is related to my installation:

Test case: https://github.com/dhoffend/crmsh/blob/test-cliparser-role/test/unittests/test_parse.py#L177

Failed job: https://github.com/dhoffend/crmsh/actions/runs/7662019057/job/20882523420?pr=2#step:5:507 



https://github.com/dhoffend/crmsh/actions/runs/7662019057/job/20882523420?pr=2#step:5:507

**Comment by liangxin1300** [comment]
@dhoffend 
When I removed this line
https://github.com/ClusterLabs/crmsh/blob/3738736c4ce2e841f6e2eccff5f8aaa00239b339/crmsh/utils.py#L3092
I got
```
>>> from crmsh import utils
>>> utils.is_ocf_1_1_cib_schema_detected()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/crmsh/utils.py", line 3284, in is_ocf_1_1_cib_schema_detected
    return is_larger_than_min_version(cib_factory.get_schema(), constants.SCHEMA_MIN_VER_SUPPORT_OCF_1_1)
  File "/usr/lib/python3.6/site-packages/crmsh/cibconfig.py", line 2471, in get_schema
    return self.cib_attrs["validate-with"]
KeyError: 'validate-with'
```

So how about try to use `cib_factory.get_cib() ` inside your ansible_pacemaker code?

**Comment by dhoffend** [comment]
@liangxin1300
I've already tried that, but it will not work out because when I initialize an empty cib, and then try to compare parts of the active mib with the parsed cli parameter that would always missmatch because of additional elements in the cib which i try to compare.

Apart from that, creating workarounds outside of crmsh will not make the unittest (https://github.com/dhoffend/crmsh/blob/test-cliparser-role/test/unittests/test_parse.py#L177) to pass successfully. 

Example: 
This unit test will pass:
```
out = self._parse('primitive st stonith:ssh params hostlist= meta')
self.assertEqual(out.get('id'), 'st')
```
while this will fail
```
out = self._parse('primitive db ocf:heartbeat:mariadb op monitor interval=29 role=Promoted op monitor interval=31 role=Unpromoted')
self.assertEqual(out.get('id'), 'db')
```

In my opinion the parser should check and validate the given commands. There shouldn't be a prerequirement to globally initialize a cib outside the Parser object. Maybe it would be better to have an optional parameter when creating a Parser object to specify a schema or assue that it is the newest supported when none is given.

To fix make the unit test work, it should be handled internally i guess.

**Comment by dhoffend** [comment]
@liangxin1300 I just realized that the packaged Debian 12 crmsh version (4.4.1-1) doesn't include the `cib_factory.get_cib()` call you mentioned. And my unit test has a different error then `validate-with`.

```
[...]
../../.tox/3.11/lib/python3.11/site-packages/crmsh/utils.py:3314: in handle_role_for_ocf_1_1
    logger.warning('Convert "%s" to "%s" since the current schema version is old and not upgraded yet. Please consider "%s"', value, downgrade_dict[value], constants.CIB_UPGRADE)
/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/logging/__init__.py:1501: in warning
    self._log(WARNING, msg, args, **kwargs)
/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/logging/__init__.py:1634: in _log
    self.handle(record)
/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/logging/__init__.py:1644: in handle
    self.callHandlers(record)
[...]

            for hdlr in c.handlers:
                found = found + 1
>               if record.levelno >= hdlr.level:
E               AttributeError: 'NoneType' object has no attribute 'level'
[...]
```
This has nothing to do with my case, but still something i came across.

The major thing I've to fix now in my ansible-pacemaker module is that the operations xml switched from attributes to nvpair elements and other things that might have changed.

Looks like I that the Debian 12 version uses an outdated and buggy version, which bug has been fixed upstream already.

**Comment by dhoffend** [comment]
P.S. The thing which is currently a bit annoying is that the `pacemaker-3.9` schema uses `operations/op` elements with `attibutes`, while the cli parser generated cib/xml somehow generates `operations/op` elements with `nvpair` subelements. This makes comparing the xmls not working.

Part of my current cib
```
<cib crm_feature_set="3.16.1" validate-with="pacemaker-3.9" epoch="7" num_updates="0" admin_epoch="0" cib-last-written="Fri Jan 26 15:03:19 2024" update-origin="ha01" update-client="crm_shadow" update-user="root" have-quorum="1" dc-uuid="1">
[...]
        <primitive id="res_ping" class="ocf" provider="pacemaker" type="ping">
          <instance_attributes id="res_ping-instance_attributes">
            <nvpair name="host_list" value="192.168.38.1" id="res_ping-instance_attributes-host_list"/>
            <nvpair name="multiplier" value="100" id="res_ping-instance_attributes-multiplier"/>
            <nvpair name="dampen" value="10" id="res_ping-instance_attributes-dampen"/>
          </instance_attributes>
          <operations>
            <op name="monitor" interval="5" timeout="60" id="res_ping-monitor-5"/>
            <op name="start" interval="0" timeout="60" id="res_ping-start-0"/>
            <op name="stop" interval="0" timeout="60" id="res_ping-stop-0"/>
          </operations>
        </primitive>
[...]
</cib>
```
Simple Test to show that the parser generates nvpairs instead of xml attributes on the op-tag
```
root@ha01:~# python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import crmsh.parse
>>> from lxml import ecmptree
>>> cmd = "primitive res_ping ocf:pacemaker:ping params host_list=192.168.38.1 multiplier=100 dampen=10 op monitor interval=5 timeout=60 op start interval=0 timeout=60 op stop interval=0 timeout=60"
>>> clip = crmsh.parse
>>> cib = clip.parse(cmd)>>> print (etree.tostring(cib, pretty_print=True).decode('utf-8'))
<primitive id="res_ping" class="ocf" provider="pacemaker" type="ping">
  <instance_attributes>
    <nvpair name="host_list" value="192.168.38.1"/>
    <nvpair name="multiplier" value="100"/>
    <nvpair name="dampen" value="10"/>
  </instance_attributes>
  <operations>
    <op name="monitor">
      <instance_attributes>
        <nvpair name="interval" value="5"/>
        <nvpair name="timeout" value="60"/>
      </instance_attributes>
    </op>
    <op name="start">
      <instance_attributes>
        <nvpair name="interval" value="0"/>
        <nvpair name="timeout" value="60"/>
      </instance_attributes>
    </op>
    <op name="stop">
      <instance_attributes>
        <nvpair name="interval" value="0"/>
        <nvpair name="timeout" value="60"/>
      </instance_attributes>
    </op>
  </operations>
</primitive>
```
I guess we can close (and open new ones) or rename this issue. The initial bug was present in 4.4 but fixed later on.

The other 2 strange behaviours are:
* something is broken with the "deprecated warning" when running the op-monitor-role in the unit test
* something is strange with operations-nvpairs when the schema expect something else

**Comment by dhoffend** [comment]
I guess we can close (and open new ones) or rename this issue. The initial bug was present in 4.4 but fixed later on.

In my ansible-pacemaker module, I've created a workaround which seems to do fine. As you suggested I've added the `cib_factory.get_cib()` call before calling the `parse()` method. If I omit this call/reset I get the strange effect, that sometimes I get operations-op-nvpairs and othertimes operations-op-attributes which is kinda unpredictable when you compare a parsed new and old command.

With this workaround (which wasn't needed with crmsh 4.2 on debian 11) I can also work around the initial issue with Debians 4.4 packaged version.

This only leaves us only left with the logging issue / deprection notice mentioned above during the unit test.

**Comment by liangxin1300** [comment]
> @liangxin1300 I just realized that the packaged Debian 12 crmsh version (4.4.1-1) doesn't include the `cib_factory.get_cib()` call you mentioned. And my unit test has a different error then `validate-with`.
> 
> ```
> [...]
> ../../.tox/3.11/lib/python3.11/site-packages/crmsh/utils.py:3314: in handle_role_for_ocf_1_1
>     logger.warning('Convert "%s" to "%s" since the current schema version is old and not upgraded yet. Please consider "%s"', value, downgrade_dict[value], constants.CIB_UPGRADE)
> /opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/logging/__init__.py:1501: in warning
>     self._log(WARNING, msg, args, **kwargs)
> /opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/logging/__init__.py:1634: in _log
>     self.handle(record)
> /opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/logging/__init__.py:1644: in handle
>     self.callHandlers(record)
> [...]
> 
>             for hdlr in c.handlers:
>                 found = found + 1
> >               if record.levelno >= hdlr.level:
> E               AttributeError: 'NoneType' object has no attribute 'level'
> [...]
> ```
> 
> This has nothing to do with my case, but still something i came across.
> 
> The major thing I've to fix now in my ansible-pacemaker module that after introducing the get_cib() command some parts that try to compare old xml command and new xml command won't match (xml looks different) or doesn't get found. I guess this is something else and has nothing to do with crmsh
> 
> Looks like I that the Debian 12 version uses an outdated and buggy version, which bug has been fixed upstream already.

Maybe you need to initialize the logger? Like what crmsh did in each module:
```
logger = log.setup_logger(__name__)
