### ISSUE TITLE
The designation of the S option seems to have a problem.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/crmsh#137]
Hi,

The S option has the following explanation, but is going to be connected to other nodes even if I appoint it.

```
[root@rh72-01 ~]# crm --version
2.1.6 (Build unknown)

[root@rh72-01 ~]# crm report help
(snip)
        -S     : single node operation; don't try to start report
                 collectors on other nodes
(snip)

[root@rh72-02 ~]# LANG=C /usr/share/crmsh/hb_report -f 8:00 -S test_216
root@rh72-01's password: 

```
Even if crm appoints S option, crm is going to handle all nodes.

Even the following correction works definitely, but I would like a more appropriate correction.

```
(snip)
                        Q) SKIP_LVL=$((SKIP_LVL + 1));;
                        L) LOG_PATTERNS="$LOG_PATTERNS $OPTARG";;
                        S) NO_SSH=1
                                USER_NODES=`uname -n`
                        ;;
(snip)
```

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

hb_report included in "glue" is it in a similar problem.
 * http://hg.linux-ha.org/glue/

If your correction is decided, I request a change in "glue".

Best Regards,
Hideo Yamauchi.

**Comment by krig** [comment]
Should be fixed with above commit, please help me verify. Thank you!

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

I confirm a correction on Monday.

Best Regards,
Hideo Yamauchi.

**Comment by krig** [comment]
Sounds good, thank you!

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

I applied your correction to crmsh2.1.6.
The S option came to work definitely.

Many Thanks!
Hideo Yamauchi.

**Comment by krig** [comment]
Great! Thank you.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

I sent the patch of the S option to "glue".
However, Mr. Dejan seems to think about hb_report of "glue" in a direction of the abolition.
 * http://www.gossamer-threads.com/lists/linuxha/dev/94600

Please send an email if there is the opinion.

Best Regards,
Hideo Yamauchi.

**Comment by krig** [comment]
Hi Hideo-san,

Yes, I saw your email and the reply from Dejan. I will let him decide what to do with cluster-glue.

@dmuhamedagic Here is the relevant issue in crmsh.

Thank you,
Kristoffer

**Comment by HideoYamauchi** [comment]
Hi Kristoffer, 

All right!

Many thanks!
Hideo Yamauchi.
