### ISSUE TITLE
license issue / question

### ISSUE THREAD

**Issue by egroeper** [ClusterLabs/crmsh#138]
Your COPYING file includes the GPLv2, but you don't provide a LICENSE file, where you state if your work is licensed solely under GPLv2 or under "any later version", too.
See section "How to Apply These Terms to Your New Programs" in the COPYING file.
Your homepage simply states "GPL" as the license.

I would like to use some of your (parsing) code in an Ansible module to configure pacemaker, that is licensed under GPLv3:
https://github.com/egroeper/ansible-pacemaker

It is really better to use your parsing code for your config file format instead of trying to parse it by myself.

So: 
Is this licensed under "GPLv2 or any later version"?
If not, would you make an exception in my case?

**Comment by krig** [comment]
Yes, crmsh is licensed under GPLv2 or any later version.

I erroneously removed this information from the `crm` command file, but have reintroduced it now. Thank you for pointing this out.
