### ISSUE TITLE
Forced optional addition is necessary for cleanup subcommand of crmsh.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/crmsh#141]
Hi All,

The operation of the C option of crm_resource is changed by Pacemaker1.1.14.

 https://github.com/ClusterLabs/pacemaker/commit/11ac60aeb7b26ac62db428e396ef421454d36153
 https://github.com/ClusterLabs/pacemaker/commit/bdcbb31094c4d2c816590e57184528e5e4273362

1) crm_resource -C -r rscid      (It is clean up from the resource of the parent.)
2) crm_resource -C -r rscid -f   (It is clean up only in a resource.)
  
Forced optional addition is necessary for cleanup subcommand of crmsh.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

A correction, thank you.
I will confirm movement tomorrow.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

I confirmed that I worked by your correction definitely.
I wait for you to release the version including the correction.

Many thanks!
Hideo Yamauchi.

**Comment by krig** [comment]
Hi Hideo-san,

Thank you for the confirmation!
