### ISSUE TITLE
Failed to install cluster-glue on Ubuntu16.04

### ISSUE THREAD

**Issue by Bhushan-IBM-17** [ClusterLabs/crmsh#151]
HI,

I have tried to install cluster glue on Ubuntu16.04 as follows :
step1 : hg clone http://hg.linux-ha.org/glue
step2 ; ./autogen.sh 
step3 ; ./configure
step4: make

but I face few issues like : logs :=>

cl_msg.c: In function 'cl_msg_add_list_str':
cl_msg.c:1346:13: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]
          !n <= 0?"n is negative or zero": 
             ^
cl_msg.c: In function 'cl_msg_add_list_int':
cl_msg.c:1399:13: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]
          !n <= 0?"n is negative or zero": 
             ^
cc1: all warnings being treated as errors

to fix that issues I tried following changes in lib/clplumbing/cl_msg.c file at line number1346 and 1399

original =>  !n <= 0?"n is negative or zero":
modified => (!n) <= 0 ? "n is negative or zero":

but on Ubuntu15.04 it run without changes also, It might be a gcc issue because on Ubuntu16.04 gcc version is : 5.4
and on Ubuntu15.04 gcc version is 4.9

Please provide some pointer regarding to same.

Thanks,
Bhushan Kalamkar

**Comment by krig** [comment]
Hi,

crmsh no longer requires cluster-glue, so you could try installing a newer version. There are pre-packaged versions of crmsh for Debian available here, which ought to work fine on Ubuntu as well: https://packages.debian.org/sid/crmsh

**Comment by Bhushan-IBM-17** [comment]
Hi,
Thanks for providing a pointer.
on similar line I look for cluster glue installation on Ubuntu16.04, that's why I raise issue.

**Comment by dmuhamedagic** [comment]
Not anymore related to crmsh, perhaps reopen at the new Clusterlabs/cluster-glue repository. Also, I believe that Kristoffer fixed the issues you found with the new gcc.

**Comment by krig** [comment]
Yes, these problems should be fixed in https://github.com/ClusterLabs/cluster-glue, please ask the Ubuntu maintainers to update cluster-glue to the latest version there.
