### ISSUE TITLE
Issue while using crm (needs Python 2.7) on centos6.4 (default Python 2.6)

### ISSUE THREAD

**Issue by swapanshridhar** [ClusterLabs/crmsh#152]
- Figured out that Python 2.6 is installed by default, and should not be messing with it as YUM needs it. So, followed this article and installed Python 2.7.
   https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4

Current situation: 
- Python 2.7 installed at '/usr/local/bin'.
   # ls /usr/local/bin
      2to3  easy_install  easy_install-2.7  idle  pip  pip2  pip2.7  pydoc  python2.7  python2.7-config     
      smtpd.py  virtualenv  wheel

```
# echo $PATH    <-------- Path has '/usr/local/bin'
/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
```

- But when I do : 
```
  # python -V
     Python 2.6.6     <--- Was expecting 2.7

   # python
      Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)        <--- Was expecting 2.7
      [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
      Type "help", "copyright", "credits" or "license" for more information.
       >>> import sys
       >>> sys.version[:3]
       '2.6'

```
- Because of above issue, "crm status" fails:
```
# crm status
   abort: minimum python version support is 2.7
```

- I also tried alias option : 
   ```
# alias python=python2.7
   
   #python -V
   Python 2.7.6

   #python
   Python 2.7.6 (default, Aug 24 2016, 23:56:06) 
   [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
   Type "help", "copyright", "credits" or "license" for more information.
   >>> import sys
   >>> sys.version[:3]
   '2.7'

   # crm status     <---- crm still doesn't get the new python version (2.7).
   abort: minimum python version support is 2.7
```

Any suggestions on how to do the setup for Python so that crm knows about it ?

**Comment by krig** [comment]
You can edit `/usr/sbin/crm` so that the first line points to `/usr/bin/python2.7`, that should be enough!

**Comment by mtcronin99** [comment]
I have the same issue.  Changing the 1st line of /usr/sbin/crm wasn't quite enough.  The crmsh python package was originally placed in /usr/lib/python2.6/site-packages and python2.7 could not find it.  I copied the crmsh* directories from /usr/lib/python2.6/site-packages to /usr/lib/python2.7/site-packages.  I also need to install python2.7-lxml.  Now it works.

**Comment by hatanoy3** [comment]
In addition, it seems to be described that "crmsh requires Python 2.6 or higher" in /usr/sbin/crm in line 56, and I tried to change "minimum_version" to "2.6", it looks working. 
Which version is required actually, and can I still using Python 2.6?

**Comment by krig** [comment]
I am releasing 2.3.1 which will be compatible with Python 2.6 again. I didn't realize the impact for centOS 6 users when moving to 2.7 as the base requirement.

**Comment by hatanoy3** [comment]
Thank you for very quick response. I'll wait for new release.

**Comment by krig** [comment]
2.3.1 packages available here now: https://build.opensuse.org/package/show/network:ha-clustering:Stable/crmsh

**Comment by mtcronin99** [comment]
will 2.3.1 be available in http://download.opensuse.org/repositories/network:/ha-clustering:/Stable/CentOS_CentOS-6/?

**Comment by krig** [comment]
It is available here, as a noarch package:

http://download.opensuse.org/repositories/network:/ha-clustering:/Stable/CentOS_CentOS-6/noarch/

Note: I haven't tested the CentOS 6 packages, so please do let me know if there are issues.
