### ISSUE TITLE
Issue installing 2.3.0 with version 2.6 of Python

### ISSUE THREAD

**Issue by breekie** [ClusterLabs/crmsh#153]
Installing the latest version of crm 2.3.0 it fails to start with error:
abort: minimum python version support is 2.7

Looking over the spec for the rpm it has the version check for python set to >=2.6

Requires:       python >= 2.6

Should the spec be upgraded to 2.7 to match what crm is checking for starting?

Thanks.

**Comment by krig** [comment]
Yes, you are right, I will fix this.

I am guessing that you are running centOS 6? You might want to stick with the 2.1.7 release since that is python 2.6 compatible. I am working on making RPM packages for that release available as well.

**Comment by breekie** [comment]
Thanks for looking into this.  Yes currently using CentOS 6. 

In terms of earlier versions, the one binary distribution I've been using is from opensuse (http://download.opensuse.org/repositories/network:/ha-clustering:/Stable/CentOS_CentOS-6/) which is version 2.3.0-1.1 ... do you happen to know if there is an older version posted somewhere else?
