### ISSUE TITLE
[Question] - crm corosync command supporting multiple rings in a node

### ISSUE THREAD

**Issue by handruin** [ClusterLabs/crmsh#154]
Hi there,

I'm looking to solve a problem for my current cluster configuration using 'crm corosync' as the interface for managing my corosync configuration and I see that in the documentation for 'crm corosync add-node' that "Note that this command assumes that only a single ring is used, and sets only the address for ring0.".  I looked at the code and I don't see a way to add additional rings to a node using this utility which confirms what the doc says.

My cluster setups will be using multiple rings in their corosync configuration and at this point I've been working on some local code to manage the corosync.conf file directly.  I think the time I spend doing that might be served better if I were to attempt to add this functionality to the crmsh project.

I am curious if this kind of change is welcomed with a new Pull request for review or are there specific reasons why this option wasn't added (e.g. extra complexity, too difficult to manage, etc) vs just not enough time to get the code written?  This isn't meant as a complaint in any way but more of a question about contributing this kind of feature back to the project if it makes sense?

**Comment by krig** [comment]
>  just not enough time to get the code written

That's pretty much it! I'm not opposed to adding support for it.

Here's the full explanation for why I didn't put in the work before: Generally, we've stopped recommending multiple rings and instead recommend bonded interfaces as the way to get network redundancy. Multiple rings works fine for corosync, but other applications and services are less likely to be able to use it, and the usefulness of having cluster communications while the service doesn't work is limited. Bonded interfaces lets you handle the same kinds of errors that redundant rings do, but the rest of the system also gains.

**Comment by handruin** [comment]
Thanks krig; that's great feedback.  I'm using corosync with Pacemaker in this example which supports the multiple rings but given what you've described I'm thinking the multiple rings are no longer needed based on your suggestion of using bonded adapters.  I'm already using a bonded adapter with a point to point connection (no switch) and was looking to add an additional adapter for the second ring.  If bonded adapters are preferred over additional rings then I'd rather not complicate the crmsh project by trying to add this in.
