### ISSUE TITLE
New "configure show" option to obscure some parameter values

### ISSUE THREAD

**Issue by kgaillot** [ClusterLabs/crmsh#155]
Pacemaker developers would like the crm_report tool to call "crm configure show" to save a readable summary of the cluster configuration to a file. However, crm_report supports a -p option to obscure sensitive information such as passwords from its generated files. -p takes a regular expression matching parameter names whose values should be obscured; the default is 'passw.*'. If a parameter name matches the pattern, its value is replaced with "****". crm_report can handle this easily for XML files, but it's next to impossible for the readable output of "crm configure show" (especially if the value contains spaces, equals signs and/or double quotes).

The idea is to have a similar option for crm, so crm_report could call something like "crm configure show --obscure='passw.*'". So instead of:

  params passwd="foo"

it would show something like:

  params passwd="****"

With crm_report, the user can specify the option multiple times to use multiple patterns. crm could do the same, or if it only supports one pattern, crm_report could combine its pattern list like '(patt1|patt2|...)' and pass that to crm.

I think this option could be useful for end users, too.

**Comment by krig** [comment]
That does seem like a useful feature.

**Comment by kgaillot** [comment]
Ha ha, sometimes you just need someone else to look at it -- it was pointed out to me that the trivial solution for crm_report is to do "crm configure show" AFTER sanitizing the CIB. Feel free to implement this for end users if desired, but I can handle crm_report now :)

**Comment by krig** [comment]
Ha! I was wondering how we were handling that in hb_report, but of course. Makes sense. ;)

Still, having direct support in crmsh would be nice, if nothing else to make the feature visible.
