### ISSUE TITLE
Question : About a change of bsc#981056.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/crmsh#156]
Hi All,

A correction to invalidate "no_quorum_policy=ignore" of bsc#981056 is included in crmsh2.1.7.
 * https://github.com/ClusterLabs/crmsh/commit/1512c0cdeca0b74dcb70c04fa4c983bc5c028d3c

We use setting of "no_quorum_policy=ignore" in a file to appoint by "crm configure load" command.

The influence of the correction of bsc#981056 is recognition to be only "cluster" command and "script" command, is my recognition wrong?

Best Regards,
Hideo Yamauch.

**Comment by krig** [comment]
Yes, this change is mainly to the configuration created by "crm cluster init". 

It is still possible to set "no_quorum_policy=ignore" via "crm configure load".

This change should not affect your usage.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Okay! Our worry cleared it!
Thank you for an early answer.

Best Regards,
Hideo Yamauchi.
