### ISSUE TITLE
unable to run crmsh on Amazon linux 2016.03.03

### ISSUE THREAD

**Issue by nwarriorch** [ClusterLabs/crmsh#157]
Hi,

So I installed crmsh version 2.3.1  form http://download.opensuse.org/repositories/network:/ha-clustering:/Stable/CentOS_CentOS-6/ on to an amazon Linux instance.

python version is 2.7.10

I have installed crmsh dependency python-lxml 2.2.3 

when I run the crm command the response is: 

 Fatal error:
        No module named crmsh

    Failed to start crmsh! This is likely due to a broken
    installation or a missing dependency.

    If you are using a packaged version of crmsh, please try
    reinstalling the package. Also check your PYTHONPATH and
    make sure that the crmsh module is reachable.

    Please file an issue describing your installation at
    https://github.com/Clusterlabs/crmsh/issues/ .

**Comment by nwarriorch** [comment]
I went ahead and took a fresh copy of amazon linux 2016.03.03 and tried to build cmrsh this time. I get through the build fine but when I run crm. I get : 

Fatal error:
        No module named crmsh
        No module named modules

    Failed to start crmsh! This is likely due to a broken
    installation or a missing dependency.

    If you are using a packaged version of crmsh, please try
    reinstalling the package. Also check your PYTHONPATH and
    make sure that the crmsh module is reachable.

    Please file an issue describing your installation at
    https://github.com/Clusterlabs/crmsh/issues/ .

**Comment by krig** [comment]
Hrm, it sounds like the python packages are being installed to the wrong location.. however, as far as I know, CentOS 6 is stuck on python 2.6. There have been issues with this before. There is no standard location for python 2.7.

It may be that crmsh is installed for Python 2.6, and that you need to call it via the python 2.6 interpreter for it to find the module.

**Comment by nwarriorch** [comment]
I got it working. Thanks for the tip on python packages. What a mess , I had to go back to previous versions where python 2.6 is the default and run the build.

**Comment by krig** [comment]
Yeah, it's a mess :(
