### ISSUE TITLE
[Request] Version 2.1.7 does not support a forced option of the cleanup.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/crmsh#158]
Hi All,

The following corrections were not included in version 2.1.7.

*  https://github.com/ClusterLabs/crmsh/commit/52c2e11406d6f6fc4fc62cb14f16ee88a20fcc97

It leaked out from the confirmation before my release.
Can you release re-release or 2.1.8 in 2.1.7 corresponding to the force option?

Best Regards,
Hideo Yamauchi.

**Comment by krig** [comment]
Hi Hideo-san,

I have released 2.1.8 with this fix included.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Great!

Many thanks!
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Sorry...A reply to you became slow.

The crmsh2.1.8 which you prepared confirmed that I worked definitely.

Best Regards,
Hideo Yamauchi.

**Comment by krig** [comment]
Hi Hideo-san,

Thank you for the confirmation!

Cheers,
Kristoffer
