### ISSUE TITLE
tmp directory continue create crmsh_xx file

### ISSUE THREAD

**Issue by guanfeix** [ClusterLabs/crmsh#1599]
![image](https://github.com/user-attachments/assets/f72dfadb-b05d-4913-9c28-62f69328896f)

Reproduce producure:
![image](https://github.com/user-attachments/assets/25bb92ab-2f48-4840-ab08-102c49d0e572)

it will create one file even though the file will be removed after process finished when run in a script every import . But in multiprocess, it seems no deletion. File number will always  increase .(Here in my python APScheduler every func call)

**Comment by guanfeix** [comment]
crmsh version and Environment:
![image](https://github.com/user-attachments/assets/a333f961-8747-495f-a648-ea4ea25501db)

**Comment by liangxin1300** [comment]
@guanfeix , we don't maintain version 3.0 anymore

**Comment by nicholasyang2022** [comment]
Close as 3.0.1 is eol. Feel free to reopen it if you have problem with the latest version.
