### ISSUE TITLE
crmsh documentaion, Syntax: Resource sets paragraph

### ISSUE THREAD

**Issue by borei74** [ClusterLabs/crmsh#160]
Hi,
I think there is typo in docs:

http://crmsh.github.io/man-2.0/#topics_Features_Resourcesets

 sequential

    If **true**, the resources in the set do not depend on each other internally. Setting sequential to true implies a strict order of dependency within the set.

but should be

 sequential

    If **false**, the resources in the set do not depend on each other internally. Setting sequential to true implies a strict order of dependency within the set.

**Comment by krig** [comment]
Thank you!
