### ISSUE TITLE
crm report does not work with dash

### ISSUE THREAD

**Issue by vvidic** [ClusterLabs/crmsh#164]
Default shell in Debian is dash rather than bash and this does not work as expected with the hb_report:

    # crm report -f 2am -M -E /var/log/syslog -d -s -Z
    /usr/share/crmsh/hb_report/hb_report: 480: local: /var/log/syslog.1: bad variable name

The problem seems to be with backtick calls returning multiple values:

    local logf_set=`arch_logs $logf $from_time $to_time`

The script should either require bash or the backtick calls need to be fixed.

**Comment by dmuhamedagic** [comment]
Yes, initialization won't work in local. Will fix that.

**Comment by vvidic** [comment]
Thanks, quoting seems to help here:

    local logf_set="`arch_logs $logf $from_time $to_time`"

However there are other backtick calls that have the same problem, so they should also be reviewed and quoted if needed.

**Comment by dmuhamedagic** [comment]
I just split out all initializations from local statements. If you have time, please test. Let us know if there are more problems with dash. Thanks!

**Comment by vvidic** [comment]
Thanks for the quick fix, no more errors :)

**Comment by krig** [comment]
Thank you both!
