### ISSUE TITLE
[Question] About the difference in version of crmsh.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/crmsh#167]
Hi All,

We investigate the use of future crmsh.

We use crmsh2.1.x now.

What is the difference with crmsh2.1.x and crmsh2.2.x and cmrsh2.3.x?
Should we shift to 2.2.x and 2.3.x in future?

Best Regards,
Hideo Yamauch.

**Comment by krig** [comment]
Hi Hideo-san,

Apologies for the late reply, I was travelling to USA for SUSEcon last week.

Yes, please move to 2.3.x in the future!

There is one new dependency on the `parallax` library: https://pypi.python.org/pypi/parallax

There are many new features in 2.3.x that are not in 2.1.x.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer ,

Okay!

I check the detailed difference in version a little, too.
We shift to 2.3.x in the future, too.

Many thanks!
Hideo Yamauchi.
