### ISSUE TITLE
python-parallax

### ISSUE THREAD

**Issue by shot4free** [ClusterLabs/crmsh#173]
Hello!
I am trying to install crmsh, but get an error about python-parallax.

`Resolving Dependencies
--> Running transaction check
---> Package crmsh.noarch 0:2.3.2-1.1 will be installed
--> Processing Dependency: python-parallax for package: crmsh-2.3.2-1.1.noarch
--> Finished Dependency Resolution
Error: Package: crmsh-2.3.2-1.1.noarch (network_ha-clustering_Stable)
           Requires: python-parallax
`
There is no information in the internet about this problem.
I think this problem is connected with similar in CentOS7.

**Comment by krig** [comment]
There are some problems with the OBS at the moment, it seems mirrors are out of sync and so on. I am hoping it will be resolved soon.

**Comment by shot4free** [comment]
Thanks. Will be checking it.

**Comment by Rohlik** [comment]
Is this resolved?

**Comment by shot4free** [comment]
Oh, I've forgot about it. I think I found some workaround. I should check it more time.
