### ISSUE TITLE
Still have some hints which unnecessarily export to users?

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#178]
Hi:
    I see some hints after input the "tab" behand "crm configure", 
    such as "_keywords/_objects/_regtest/_test", which is not documented,
    I think these hints unnecessarily export to users
    My version is 2.3.2
    Regards,
    Xin

**Comment by krig** [comment]
Ah, those should probably be hidden from tab completion, yeah. Good catch!
