### ISSUE TITLE
Function 'is_process' always return True

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#182]
crmsh.utils.is_process

even the processname is not running or illegal

I think "ps -ef|grep -v grep|grep -q %s" is better

**Comment by krig** [comment]
oh, good catch!

**Comment by liangxin1300** [comment]
But it still not work
Please check that
When crmd is running
ps -ef -o comm= | grep -v grep | grep -qsE '\bcrmd\b' ==> return 1
