### ISSUE TITLE
About time convert

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#183]
crmsh.utils.parse_to_timestamp("2pm")   --> 1487916000.0
crmsh.utils.timestamp_to_datetime(1487916000.0).strftime("%Y-%m-%d %H:%M")  --> '2017-02-24 06:00'

But, when I use shell:
echo "1487916000.0"|awk '{ print strftime("%Y-%m-%d %H:%M", $1); }' --> 2017-02-24 14:00

I think "2pm" convert to "2017-02-24 14:00" is right
So, is there some problems in function "timestamp_to_datetime"?

**Comment by krig** [comment]
The question is, what timezone are you in? When I run `crmsh.utils.parse_to_timestamp("2pm")`, I get

```
In [9]: crmsh.utils.parse_to_timestamp("2pm")
Out[9]: 1487941200.0
```

`parse_to_timestamp` is not designed to parse ambiguous time definitions, and tries to convert dates that don't have an explicit timezone specifier from whatever the local timezone is into UTC.
