### ISSUE TITLE
what is the cts test number?

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#184]
In hb_report, there is an option followed with "-f": "cts:"testnum
I have no idea how to use it. Which test number cloud be used?

Regards,
Xin

**Comment by krig** [comment]
CTS is the test suite for pacemaker: https://github.com/ClusterLabs/pacemaker/tree/master/cts

In hb_report, the option for cts is used to get the time span (from - to) from a CTS test case after running the test suite. So if you have a failing test, you can get logs etc. from all nodes for the duration of the failing test using that option.
