### ISSUE TITLE
Centos7.3 install crmsh via ISO installation not possible due to crmsh package requires missing /bin/python

### ISSUE THREAD

**Issue by zbalogh** [ClusterLabs/crmsh#192]
I downloaded crmsh and its dependencies from opensuse repository. After CentOS 7.3 setup If I install these RPM files by "rpm" command via CLI then it works. However if I add these RPM files into my custom ISO file (built by me, resolved all dependecies) then the installer prompts the following error:

"Error checking software selection"

If I click on the "Software Selection" button, and choose "Click for details" then it says:

crmsh-3.0.0-2.2.noarch requires /bin/python
python-parallax-1.0.1-29.1.noarch requires /bin/python

It seems when CentOS 7.3 checks and verifies the repository for all RPM packages then it detects that crmsh and python-parallax RPMs depends on both /bin/python and /usr/bin/python. that should be the problem. I assume it should be depending only on /usr/bin/python.

referring to other issue: https://github.com/ClusterLabs/crmsh/issues/161

Can you please investigate it and recommend a possible fix/solution for that?

Thanks a lot!

Zoltan

**Comment by Rohlik** [comment]
Dupplicate with https://github.com/ClusterLabs/crmsh/issues/161

**Comment by GLaN1K** [comment]
Unfortunately, got this too.
What information is needed to investigate this?
