### ISSUE TITLE
A little confuse about crmsh.ui_cluster.Cluster.__doc__

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#213]
Hi @krig:

 in crmsh.ui_cluster.Cluster__doc__:
    `- Package installation` 
confuse me
   crmsh->cluster will install some packages?

**Comment by krig** [comment]
That was one of the ideas from the beginning, so for example `cluster init` would be smart enough to try to install missing packages if detected. I think there are some examples of that in the wizards...
