### ISSUE TITLE
Is crm->cluster->bootstrap the alternative of ha-cluster-bootstrap?

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#234]
hi krig:

Is crm->cluster->bootstrap the alternative of ha-cluster-bootstrap?
Will the package ha-cluster-bootstrap not in ha packages group?
If so, we should find another way to invoke ssh_remote/csync2_remote on the remote node;
for now, ha-cluster-init shell script is used to do these.

regards,
xin

**Comment by krig** [comment]
ah yes, crm cluster bootstrap is the replacement for ha-cluster-bootstrap: The idea is that the "ha-cluster-init" script just calls "crm cluster init".
