### ISSUE TITLE
crm cluster init: sbd systemd service options

### ISSUE THREAD

**Issue by vvidic** [ClusterLabs/crmsh#235]
Cluster bootstrap updates the SBD config file with ``SBD_DEVICE`` and ``SBD_WATCHDOG`` options but [systemd service](https://github.com/ClusterLabs/sbd/blob/master/src/sbd.service.in) only takes ``SBD_OPTS`` from there:

    EnvironmentFile=-@sysconfdir@/sysconfig/sbd
    ExecStart=@sbindir@/sbd $SBD_OPTS -p @localstatedir@/run/sbd.pid watch

Is there a better service file available, or should the bootstrap script be updated to generate ``SBD_OPTS`` instead?

**Comment by krig** [comment]
Ah, but the options get injected into the environment for the sbd executable (via EnvironmentFile), and sbd doesn't just look at the command line options: It also reads the environment variables directly. At least this is true for the more recent versions of sbd.

**Comment by vvidic** [comment]
Thanks for checking, it looks that sbd does indeed start correctly but stonith agent did not load the configuration and failed, so I'll fix that part.

**Comment by vvidic** [comment]
Ouch, it seems that SBD_WATCHDOG is not used by the sbd daemon (only SBD_WATCHDOG_DEV) so there is no way to disable watchdog in sbd?

**Comment by krig** [comment]
Aah right, this was a bug that *should* be fixed in crmsh now, with commit a1700c3bc21f57b711874c3e502dc1bfbd8823d3.

**Comment by vvidic** [comment]
Please review the pull request to fix the second instance of SBD configuration.
