### ISSUE TITLE
bootstrap or cluster lock?

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#243]
Hi @krig:
    When having more than two nodes to configure cluster, and, 
    when some nodes run "crm cluster join" to join a configured node simultaneously, 
    the csync2 will failed.

It's better to join a configured node **one by one**.
    To implement this, 
    (e.g. node A has been configured, node B and node C want to join)

1) touch a hidden lock file on the node A when node B want to join, and excluding node C until node B's join process done
2) remove the hidden lock file on node A when node B finished join process
3) leave the interface "do_lock" and "do_unlock" in ui_cluster, it's convenient to touch and remove the lock file manually 

Any suggestion will be appreciated:)
Regards,
xin

**Comment by krig** [comment]
Ah yeah, that's a really good idea. The only issue is in the case of a failed join, the lock file might be left on the node. In that case, it would block future attempts to join.
I would say at the very least, there should be a clear message printed when blocking, and an option to ignore:
"Cannot join cluster while another node is joining. Lock found on remote node (override with --ignore-lock)."

**Comment by liangxin1300** [comment]
Thanks for suggestion!

**Comment by liangxin1300** [comment]
Close it
For latest implement, see https://github.com/ClusterLabs/crmsh/pull/677 and https://github.com/ClusterLabs/crmsh/pull/694
