### ISSUE TITLE
Unable to start crmsh due to missing lxml module

### ISSUE THREAD

**Issue by absen7** [ClusterLabs/crmsh#281]
** **Would appreciate if I get genuine links to install the mandatory Py modules for crmsh ( excluding crmsh & setuptools ) / get the RPM links to resolve the lxml dependencies****

Hi there, I have configured 2 SLES VM's in a cluster using the SLES HA extension pack on an unicast mode. I am having trouble in starting the crm shell to manage the cluster from the CLI due to "**missing lxml"** module. FYI, i have already installed the CRMSH module in my library and also installed most of the packages that came with the SLES HA pack. I even tried building an entirely new crmsh package, and soft-linked the installed contents to one of the $PYTHONPATH directories. However, every time I start crmsh, I get

**_absensles1:/etc/crmsh-3.0.1 # crm
Fatal error:
        **No module named lxml**

    Failed to start crmsh! This is likely due to a broken
    installation or a missing dependency.

    If you are using a packaged version of crmsh, please try
    reinstalling the package. Also check your PYTHONPATH and
    make sure that the crmsh module is reachable.

    Please file an issue describing your installation at
    https://github.com/Clusterlabs/crmsh/issues/ .
absensles1:/etc/crmsh-3.0.1 #_** 

When I try to install the python-lxml module ( which is not yet loaded into the RPM DB and exists as a srcpackage) , 

absensles1:/etc/crmsh-3.0.1 # zypper se python-lxml
Loading repository data...
Reading installed packages...

S | Name        | Summary                                      | Type      
--+-------------+----------------------------------------------+-----------
  | python-lxml | Powerful and Pythonic XML processing library | srcpackage

absensles1:/etc/crmsh-3.0.1 # zypper source-install "python-lxml"
Reading installed packages...
Loading repository data...
Resolving package dependencies...

Problem: nothing provides libxml2-devel needed by python-lxml-3.3.3-1.2.src
 Solution 1: do not ask to install a solvable providing python-lxml.src = 3.3.3-1.2
 Solution 2: break python-lxml-3.3.3-1.2.src by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c):

**Comment by krig** [comment]
Which version of SLES is this?

**Comment by absen7** [comment]
SLES11 SP4

**Comment by krig** [comment]
It's strange that you don't have the python-lxml package, it should be on the media as well as in the channel. Plus, the crmsh rpm has a Requires for it so it shouldn't even install if that package isn't available. How did you install the HA addon?

**Comment by absen7** [comment]
Downloaded the HA extension ISO file from the SLES repo and then through the  YAST Product Add+on+ Software manager. 
 The cluster is built perfectly and I can monitor them on Hawk as well as Pacemaker UI ( does SLES provide pcs on the CLI?) although I haven't configured any resource yet

**Comment by krig** [comment]
If hawk is working you should already have crmsh installed on the cluster nodes as it's what hawk uses to talk to the cluster as well. There's no need to download or install crmsh separately.

**Comment by absen7** [comment]
I know. But I have to get the crm running on the CLI. I'd prefer managing the cluster resources on the backend rather than firing up the HAWK UI always

**Comment by krig** [comment]
I mean that you already have it on the CLI :) You'll need to SSH to the nodes as the hacluster user or as root, crm is installed to /usr/sbin/crm.

**Comment by absen7** [comment]
I agree with all of that Kris. I am calling the crm shell after root login on both the nodes. I also logged into Hawk and tried configuring the OCFS2 resource but it failed on HAWK UI as well flashing the same below error. As a workaround, I'm reinstalling SLES12 SP2 on two nodes along with the SLES 12SP2 Online SDK repo and the HA extension for the same version+SP 

-----------++---------++------++--------------
No Module named lxml
Failed to start crmsh! This is likely due to a broken
installation or a missing dependency.

If you are using a packaged version of crmsh, please try
reinstalling the package. Also check your PYTHONPATH and
make sure that the crmsh module is reachable.

Please file an issue describing your installation at
https://github.com/Clusterlabs/crmsh/issues/ .
------+++--------+++------------------++--------

**Comment by krig** [comment]
Well, that is really strange. It could be that they've messed up the repositories somehow. I'll investigate.

**Comment by absen7** [comment]
Thanks. New installation works now ( at least crmsh :P ) I will keep you posted after I configure the 2 node cluster successfully. I have sent out a LinkedIN/Facebook connect req. to you, will be great to stay connected.

**Comment by krig** [comment]
Haha, I don't know how much you'll enjoy my Facebook feed, I mostly post music videos ;) But sure! Let me know how it goes.
