### ISSUE TITLE
corosync: [Errno 2] No such file or directory: '/proc/156490/cmdline'

### ISSUE THREAD

**Issue by handruin** [ClusterLabs/crmsh#283]
I'm tracking down and issue when running a command such as:
/usr/sbin/crm corosync set logging.timestamp on
(note that this is not specific to the "set logging.timestamp on" command, it happens with others.

If I've seen the following non-zero return with an error:
corosync: [Errno 2] No such file or directory: '/proc/156490/cmdline'

Since this happens randomly on my system, I put this command in a loop and added strace to it to try and capture more details.

What I'm seeing as a symptom is that the code is iterating through all my linux /proc/<pid>/cmdline.  I'm making a guess that the failure might be the result of some other process terminates (gracefully) while this loop is iterating and it cannot find a pid that was stored in memory when the pids were listed and stored in a variable.

> read(3, "strace\0/usr/sbin/crm\0corosync\0se"..., 8192) = 55
> read(3, "", 7168)                       = 0
> close(3)                                = 0
> munmap(0x7f5191247000, 4096)            = 0
> open("/proc/156489/cmdline", O_RDONLY)  = 3
> fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
> fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
> lseek(3, 0, SEEK_CUR)                   = 0
> fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
> mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5191247000
> lseek(3, 0, SEEK_CUR)                   = 0
> read(3, "/usr/bin/python\0/usr/sbin/crm\0co"..., 8192) = 64
> read(3, "", 7168)                       = 0
> close(3)                                = 0
> munmap(0x7f5191247000, 4096)            = 0
> **open("/proc/156490/cmdline", O_RDONLY)  = -1 ENOENT (No such file or directory)**
> write(2, "ERROR: corosync: [Errno 2] No su"..., 76ERROR: corosync: [Errno 2] No such file or directory: '/proc/156490/cmdline') = 76
> write(2, "\n", 1
> )                       = 1
> rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x392ca0f7e0}, {0x392cf033f0, [], SA_RESTORER, 0x392ca0f7e0}, 8) = 0
> exit_group(1)                           = ?
> +++ exited with 1 +++

I noticed that inside the file /crmsh/utils.py there is a function named "is_process" that iterates over all found processes.  It looks like @krig added/refactored this about 7 months ago per git blame.

The code does the following exception handling which it has the intent of handling the situation I've witnessed:
`        **except os.error:**
            # a process may have died since we got the list of pids
            pass`

From my own little unit test under Python 2.6, the actual exception being thrown is of **IOError**.   
 This means the except clause is not handling the missing pid directory.  If I change the catch clause to handle IOError, this problem is fixed in my unit testing.  I can issue a PR with this fix if that's helpful?  I don't have a newer Python to test against to ensure it's compatible.

**Unit test:**

`def is_process(s):
    """
    Returns true if argument is the name of a running process.
    s: process name
    returns Boolean
    """
    from os.path import join, basename
    # find pids of running processes
    pids = [pid for pid in os.listdir('/proc') if pid.isdigit()]
    for pid in pids:
        try:
            cmdline = open(join('/proc', pid, 'cmdline'), 'rb').read()
            procname = basename(cmdline.replace('\x00', ' ').split(' ')[0])
            if procname == s:
                return True
        except IOError:
            # a process may have died since we got the list of pids
            print 'IO error found...'
            pass
    return False

is_process('test')`

`for i in {1..100}; do ./unit-tests-platform.py || break; echo $?; done`
0
0
IO error found...
IO error found...
0
IO error found...
IO error found...
0

**System:**
CentOS 6.9 (2.6.32-696.6.3.el6.x86_64)

**Packages**
- rpm -qa | egrep "pacemaker|crm|corosync"
- drbd-pacemaker-8.9.8-1.el6.x86_64
- crmsh-3.0.1-0.noarch
- corosync-2.4.2-1.el6.x86_64
- pacemaker-cli-1.1.17-1.el6.x86_64
- pacemaker-doc-1.1.17-1.el6.x86_64
- pacemaker-cts-1.1.17-1.el6.x86_64
- pacemaker-remote-1.1.17-1.el6.x86_64
- crmsh-scripts-3.0.1-0.noarch
- corosynclib-2.4.2-1.el6.x86_64
- pacemaker-cluster-libs-1.1.17-1.el6.x86_64
- pacemaker-libs-devel-1.1.17-1.el6.x86_64
- pacemaker-1.1.17-1.el6.x86_64
- pacemaker-libs-1.1.17-1.el6.x86_64
- corosynclib-devel-2.4.2-1.el6.x86_64

**This is how I reproduce it:**
`for i in {1..100}; do strace /usr/sbin/crm corosync set logging.timestamp on &> /tmp/crm_strace_$i.log || break; echo $?; done`

**Comment by handruin** [comment]
Hopefully I did things correctly with the process.  I added in a PR https://github.com/ClusterLabs/crmsh/pull/284.  Let me know if you would like a different solution to this or if you have any questions/issues with my changes.  Thanks for the consideration.

**Comment by krig** [comment]
Should be fixed by #284.
