### ISSUE TITLE
crmsh.spec has old version defined causing RPM build failure with newer releases

### ISSUE THREAD

**Issue by handruin** [ClusterLabs/crmsh#285]
I'm not sure if this is intentional but the spec file has this version defined:
**Version:        2.3.0**

This causes issues when building the RPM because the tar.bz2 cannot be located.  I get the following error:

> error: File /home/build/rpmbuild/SOURCES/crmsh-2.3.0.tar.bz2: No such file or directory

Here are the steps I use:

```
export CRMSH_VERSION="3.0.1"
tar -cvjSf crmsh-${CRMSH_VERSION}.tar.bz2 crmsh-${CRMSH_VERSION}
mkdir -p /home/build/rpmbuild/SOURCES/
mv -f crmsh-${CRMSH_VERSION}.tar.bz2 /home/build/rpmbuild/SOURCES/
rpmbuild -bb --nosignature crmsh-${CRMSH_VERSION}/crmsh.spec

```

To get around this issue I've simply been using sed to replace the version number inside the spec file with the one I'm trying to build.  The build works fine after that.

`sed -i \"s/Version:        2.3.0/Version:        ${CRMSH_VERSION}/g\" ./crmsh-${CRMSH_VERSION}/crmsh.spec`

I can try to come up with a dynamic way of getting the version based on the git client querying the version that's checked out so that this value isn't breaking each person who wants to build a different release and do a PR.  I'm not sure how you would like this managed for building RPMs.

Something like adding:
```
%define version %(git describe --tags)
Version: %{version}
```

**Comment by krig** [comment]
We are not great at keeping the checked in spec file up to date, sorry... We could perhaps change the spec file to be generated by the Makefile, like other `.in` files, so that we could get the version from there.

**Comment by handruin** [comment]
No worries.  You suggestion is a better solution than what I proposed.  It's not blocking me or anything.  I use sed to replace the version when automating my own build.
