### ISSUE TITLE
Do we need a `rule` sub-command in ui_configure?

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#329]
Hi krig,
For now, edit a rule in crmsh is not easy.
Is it necessary that adding a 'rule' sub-command in ui_configure.py?
We can use specific completer to make configure things easier.

After doing that, we can further improve our constraints completer, of cause can using the rule id-ref:)

Regards,
xin

**Comment by krig** [comment]
Can you explain a bit more how you would like the rule sub-command to work?

**Comment by liangxin1300** [comment]
I think I have misunderstanding for it.
rule element can not stay alone at cib file, it should be included by constraints elements
