### ISSUE TITLE
configure->erase is dangerous

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#342]
After running erase, cluster service can not stop.

Maybe we should not leave this interface to user, even he is 'administrator',
like a OS will not leave an interface for doing 'rm -rf /' ：）

If we do have reason to keep this sub-command, add an interactive confirm is better.
And then,  we should figure out how to stop cluster service force.

Regards,
xin

**Comment by zzhou1** [comment]
I incline to agree to deprecate this one, and tell the end user the equivalent replacement to achieve the use case could be
`crm cluster remove --force`

**Comment by liangxin1300** [comment]
Since there were lots of places using this command in original regression test
It's not easy to drop this command
