### ISSUE TITLE
change 'env python' and 'python' to specific python major version to ease porting to other OS/distro

### ISSUE THREAD

**Issue by jirib** [ClusterLabs/crmsh#360]
Hi,

I'm porting corosync/pacemaker (done) and crmsh to OpenBSD and I discovered there's tons of 'env python' or 'python' in your scripts. Unfortunatelly there's no 'python' on OpenBSD, there's 'pythonX' where 'X' is major version, ie. 'python2' or 'python3'.

It would be much easier for porting crmsh to other OS/distros if this would be taken into account.

Is python3 required or is there still a kind of freedom to choose major version? I see crmsh in AUR still uses python2 for example.

Thanks!

**Comment by krig** [comment]
Hi! For the version in `master` - the 4.0 branch - Python 3 is required. What we do for openSUSE is scan through and replace all the shebangs at build time, which is a bit of a hack admittedly..

For older versions, <= 3, Python 2 is required. So there's no version of crmsh which supports both 2 and 3.
