### ISSUE TITLE
Detect -h for crm configure property

### ISSUE THREAD

**Issue by tomschr** [ClusterLabs/crmsh#367]
When using the command `crm configure property -h` it gives the following warning:

```
# crm configure property -h
WARNING: cib-bootstrap-options: unknown attribute '-h'
```

I would have expected that it prints a help message similar to `crm configure help property`. Or at least recognize that `-h` isn't a valid property name. :wink:

However, what's worse is, the command writes `-h` into the CIB:

```
# crm configure show
[...]
property cib-bootstrap-options: \
        have-watchdog=true \
        dc-version="1.1.18+20180313.2c83c6872-1.1-2c83c6872" \
        cluster-infrastructure=corosync \
        cluster-name=hacluster \
        stonith-enabled=true \
        placement-strategy=balanced \
        enable-acl=true \
        have-watchdog \
        no-quorum-policy \
        -h
[...]
```

As you can see, the `-h` appears in the CIB. I'm pretty sure, you don't want that. :wink:

**Comment by krig** [comment]
yeah, I've thought about that, it is not very convenient to write "help property" rather than arrow-up and adding "-h" or "--help" as the last parameter. This would be a nice feature indeed. I'm wondering if there is any place where adding this feature might interfere with existing functionality... what if you want to set the value of a parameter to `"-h"`? although that should hopefully not be a common thing :p

**Comment by tomschr** [comment]
> what if you want to set the value of a parameter to "-h"? although that should hopefully not be a common thing :p

I hope, this would never be the case a parameter with a name `-h`. :wink: Well, lets assume for a moment we want that. Wouldn't this be parsed by the respective argparse module? I'm thinking of something like this:

```shell
crm configure property -- -h
```

Anyway, IMHO the crm shell should catch some user errors *before* the user can do something wrong. If someone uses `-h` to get help, it is not very uncommon. :wink:  IMHO, this should be correctly parsed and handled.

**Comment by krig** [comment]
I agree! I will look into it.
