### ISSUE TITLE
[Question] Exception occurrence in crm shell.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/crmsh#398]
Hi All,

A strange exception occurred in our user's environment.
In the environment of Pacemaker 1.1.16 of RHEL 7.2, the crm shell is using a bit older 2.1.9.

The events that occurred by the user are as follows.

Step 1) Execute "crm status xxx" command Create Pacemaker Alert script.
Step 2) Start up the cluster that executes Alert.
Step 3) When stopping Pacemaker, the Alert script was also executed.

Then, the following mail arrived from abrt_server.

```
(mail)
>N  1 xxxxxxxxxxxx  Tue Oct  2 15:10 103/3462  "[abrt] crmsh: os.py:157"
　
:os.py:157:makedirs:OSError: [Errno 17] File exists: '/root/.cache/crm'
:
:Traceback (most recent call last):
:  File "/sbin/crm", line 56, in <module>
:    rc = main.run()
:  File "/usr/lib64/python2.7/site-packages/crmsh/main.py", line 365, in run
:    userdir.mv_user_files()
:  File "/usr/lib64/python2.7/site-packages/crmsh/userdir.py", line 74, in mv_user_files
:    HISTORY_FILE = _xdg_file(HISTORY_FILE, "history", os.path.isfile, CACHE_HOME)
:  File "/usr/lib64/python2.7/site-packages/crmsh/userdir.py", line 61, in _xdg_file
:    os.makedirs(directory, 0700)
:  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
:    mkdir(name, mode)
:OSError: [Errno 17] File exists: '/root/.cache/crm'
:
:Local variables in innermost frame:
:tail: 'crm'
:head: '/root/.cache'
:name: '/root/.cache/crm'
:mode: 448

(messages)
Oct  2 15:10:24 e99musash-sgea921000 <user.notice> python:detected unhandled Python exception in '/sbin/crm'
Oct  2 15:10:29 e99musash-sgea921000 <user.notice> python:communication with ABRT daemon failed: timed out

```

Apparently, when a problem occurred, multiple alerts were executed at the same time.

The problem occurred only once in the user's environment, but it is unknown that the corresponding exception occurred. 
Usually I do not think it will happen.

Is there anyone who encountered similar events?
Can someone guess the mechanism that occurred?

Best Regards,
Hideo Yamauchi.

**Comment by krig** [comment]
Hi Hideo-san,

This is an issue I have not seen before! It would affect any version of crmsh. It seems like this could only happen if a file exits named `/root/.cache/crm`, since crmsh checks if it is an existing directory. In the case when `/root/.cache/crm` exists but is a file, it may get confused. Could this be the case?

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

I am carrying out a reproduction test with loop-like execution in the environment at hand.
For now, since the user's reproduction is only once, I do not know whether to reproduce it or not.

I will try out the test until tomorrow.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

After all, it was impossible to reproduce the phenomenon.
I think that there is a possibility that some other process (eg virus detection process etc.) and a problem such as OS are related, but it seems to be difficult to reproduce easily.

I will investigate a little more and I will close this issue.

Many thanks,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
HI  Kristoffer,

I examined various things, but the cause of the problem was unknown.
The problem did not reproduce.

I will investigate again when the same problem occurs.

This issue is closed.

Many thanks,
Hideo Yamauchi.

**Comment by krig** [comment]
Thank you!
