### ISSUE TITLE
Better to articulate `crm cluster stop` INFO output

### ISSUE THREAD

**Issue by zzhou1** [ClusterLabs/crmsh#413]
~ # crm cluster stop
INFO: Cluster services stopped

Basically, the term of "services" can be systemd services, ie, pacemaker.service, corosync.service, sbd.service. Also, it is widely used to refer to cluster resource agents to the end user.

So, better to improve INFO to clarify about this command. Eg, it stops the whole stack, both resource agents and systemd pacemaker/corosync.service/services.

I can understand the code. It stops corosync.service. The consequence result is a graceful shutdown of pacemaker which stops all resource agents on top.

**Comment by krig** [comment]
Good idea, yes :)
