### ISSUE TITLE
crmsh problems

### ISSUE THREAD

**Issue by GitSoftwareNow** [ClusterLabs/crmsh#438]
crm(live)# configure
ERROR: running cibadmin -Ql: Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations
ERROR: configure: Missing requirements

**Comment by krig** [comment]
Sounds like you don't have a cluster running! At least this is the message you get when crmsh is unable to connect to Pacemaker. You should get the same error if you try to run `cibadmin -Ql` as well.

**Comment by GitSoftwareNow** [comment]
when I run cibadmin -Ql but is says
Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

**Comment by GitSoftwareNow** [comment]
when I run cibadmin -Ql but is says
Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

**Comment by krig** [comment]
Sounds like there is no cluster running!

**Comment by GitSoftwareNow** [comment]
crm(live)# configure
ERROR: running cibadmin -Ql: Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations
ERROR: configure: Missing requirements


ldirectord corosync pacemaker is running

**Comment by krig** [comment]
The problem is not with crmsh, but with your installation.

**Comment by ghevge** [comment]
I am facing the same problem:

```
cibadmin -Q
Could not connect to the CIB: Transport endpoint is not connected
cibadmin: Init failed, could not perform requested operations: Transport endpoint is not connected
```

As you can see below I do have a cluster up and running but still the cibadmin is not able to connect. How exactly is this took working? To what componet is is supposed to connect ? Any suggestions on how I can  try todebug this problem ? There is little to no clear information on the web about this.

```
[adm@server1 crmsh-4.5.0]$ sudo pcs status
[sudo] password for adm:
Cluster name: nfsCluster
Cluster Summary:
  * Stack: corosync (Pacemaker is running)
  * Current DC: server2.test (version 2.1.6-4.fc38-6fdc9deea29) - partition with quorum
  * Last updated: Wed Jul 12 12:02:00 2023 on server1.test
  * Last change:  Wed Jul 12 11:47:28 2023 by root via cibadmin on server1.test
  * 2 nodes configured
  * 0 resource instances configured

Node List:
  * Online: [ server1.test server2.test ]

Full List of Resources:
  * No resources

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled


```

**Comment by ghevge** [comment]
My cluster was configured following this procedure: https://www.simplified.guide/pacemaker/create-cluster

**Comment by ghevge** [comment]
Hmm on my end it started to work once I've run it with sudo. So it turned out to be a permission problem. Maybe the error message should be improved to reflect what exactly is causing the problem
