### ISSUE TITLE
ldirectord corosync pacemaker is running

### ISSUE THREAD

**Issue by GitSoftwareNow** [ClusterLabs/crmsh#439]
ldirectord corosync pacemaker is running but 
crm(live)# configure
ERROR: running cibadmin -Ql: Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations
ERROR: configure: Missing requirements

ldirectord corosync pacemaker is running

**Comment by krig** [comment]
The problem is not in crmsh, but in your installation.
