### ISSUE TITLE
An error occured on my linux server

### ISSUE THREAD

**Issue by GitSoftwareNow** [ClusterLabs/crmsh#440]
crm status
ERROR: status: crm_mon (rc=134): Connection to cluster failed: Transport endpoint is not connected
 
what's wrong of number 143? how can I resolve it? ldirectord corosync pacemaker is running?

**Comment by GitSoftwareNow** [comment]
crm status
ERROR: status: crm_mon (rc=134): Connection to cluster failed: Transport endpoint is not connected

what's wrong of number 143? how can I resolve it? ldirectord corosync pacemaker is running now

**Comment by diegoakechi** [comment]
@GitSoftwareNow  Similar to issue #438, please, make sure you have a cluster proper running and configured.

You can get a quick start guide here: https://www.suse.com/documentation/sle-ha-12/singlehtml/install-quick/install-quick.html

Please, follow these steps, and if crmsh still does not work, please, open an issue.
