### ISSUE TITLE
Can not remove or add the nodes

### ISSUE THREAD

**Issue by GitSoftwareNow** [ClusterLabs/crmsh#451]
When I use such those commands "crm cluster add node name", "crm cluster remove nodename"  it says "INFO: Initialize a new cluster
INFO: Nodes: ha1, ha2
ERROR: [ha2]: Start: Exited with error code 255, Error output: command-line: line 0: Bad configuration option: ControlPersist
ERROR: [ha2]: Clean: Exited with error code 255, Error output: command-line: line 0: Bad configuration option: ControlPersist
ERROR: cluster.init: Failed to connect to one or more of these hosts via SSH: ha2"

**Comment by liangxin1300** [comment]
Hi @GitSoftwareNow , which distribution version and crmsh version do you use?

**Comment by GitSoftwareNow** [comment]
> Hi @GitSoftwareNow , which distribution version and crmsh version do you use?

2.3.1

**Comment by GitSoftwareNow** [comment]
@liangxin1300 2.3.1

**Comment by liangxin1300** [comment]
Hi @GitSoftwareNow , which OS version do you use?

**Comment by GitSoftwareNow** [comment]
@liangxin1300 CentOS 6.4 OS
