### ISSUE TITLE
python3 support bug

### ISSUE THREAD

**Issue by ckonstanski** [ClusterLabs/crmsh#454]
I am attempting to run crmsh on gentoo. Here is the package info:

[ebuild  N    ~] sys-cluster/crmsh-3.0.3::gentoo  PYTHON_TARGETS="python3_5 python3_6 python3_7" 927 KiB

Note it only comes with support for python3.x.

When trying a simple command like crm configure show, I immediately run into an error that is indicative of python2 code not being properly ported to python3 (python3.5 in this case):

root@haproxy-1:/etc/init.d # crm configure show
Traceback (most recent call last):
  File "/usr/bin/crm", line 35, in <module>
    from crmsh import main
  File "/usr/lib64/python3.5/site-packages/crmsh/main.py", line 271
    print "Ctrl-C, leaving"
                          ^
SyntaxError: Missing parentheses in call to 'print'

I tried with python3.5, 3.6 and 3.7. Same results for all.

**Comment by ckonstanski** [comment]
I see that the bug is fixed in master. I'll take this up with the gentoo package maintainers. They need to update the package.

**Comment by krig** [comment]
@ckonstanski Thank you for reporting this! Yes, we moved to Python 3 after the crmsh 3 release. The release tags haven't been updated in a while but master is very stable, so for anyone packaging crmsh on a distribution that uses Python 3, I would recommend packaging git master.

**Comment by ckonstanski** [comment]
It would be helpful if a release tag could be made that had these fixes. I can imagine that a package maintainer would not want to base a package off of master since it'S a constantly moving target.

**Comment by krig** [comment]
Yes, I agree. :)

**Comment by ckonstanski** [comment]
A bit of cross-linking: https://bugs.gentoo.org/669568

I'm going to reopen this issue because a tag is necessary.

**Comment by diegoakechi** [comment]
@ckonstanski @krig, I have tagged the version 4.0.0 and 4.1.0, being these the main versions when we migrated crmsh to python3 only. Based on many bugfixing and also pacemaker 2.0 compatibility, I recommend using the 4.1.0 version. I am closing this issue for now. Please, let me know in case of any problem.

Thanks again for reporting and using crmsh!

**Comment by ckonstanski** [comment]
Much appreciated!
