### ISSUE TITLE
Compiling on rhel7 

### ISSUE THREAD

**Issue by chilicat** [ClusterLabs/crmsh#46]
I try to build crmsh on rhel7 but I get following error:

```
./configure
....
checking for glue_config.h... no
configure: error: in `/root/crmsh':
configure: error: Core development headers were not found
```

It seems like that "libcluster-glue-dev " package is missing. I couldn't find this package in the rhel7 distribution.

Any idea where I can find the package? Or maybe the package has been renamed?

**Comment by krig** [comment]
The development headers are no longer required for building crmsh unless the test suite is enabled. Please give it another try!
