### ISSUE TITLE
Question on modifying an existing resource op monitor parameter

### ISSUE THREAD

**Issue by handruin** [ClusterLabs/crmsh#474]
Hi,

I've been reading through the doc trying to figure out if it's possible to script a change to a primitive monitor definition using the crmsh utility.  I need to edit a bunch of clusters with stonith primitives to specifically add a new key/value of **on-fail=ignore** to the **op monitor** section.  I cannot find the right command line option to add this new value specifically to the op monitor section.  Does the crmsh utility support modifying this op monitor section of a resource primitive via a single command line operation?  I know I can use the command `crm config edit` and change it manually but I need to script this.

Example primitive definition:
> primitive stonith-fence0 stonith:fence_ipmilan
params pcmk_host_list=dcdev0 ipaddr=xxx.xxx.xxx.xxx login=stonith passwd="xxxxxxxxx" lanplus=1 pcmk_monitor_timeout=3600s pcmk_monitor_retries=500
> op monitor interval=60s **on-fail=ignore**

**Comment by liangxin1300** [comment]
Hi @handruin , thanks for using crmsh and thanks for your suggestions!
I've created a PR for this, see #514 
with this new PR, in above case, you could do it like:
```
crm configure set stonith-fence0.monitor.on-fail ignore
```
