### ISSUE TITLE
sbd.service failed to enable on join node

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#574]
It seems a bit of tricky here.
For scenarios of bsc#1166967, SBD resource still be configured even not specify with '-s' option while re-configuring on init node;
And on join node, sbd service still started only if found sbd configured;
Then I created PR https://github.com/ClusterLabs/crmsh/pull/545/files to fix above issue
but forget that join node doesn't know whether init node has specified -s option, so the value of _context.sbd_device always None on join node

For now I have three ideas:

1. Comment out or remove SBD_DEVICE line in sysconfig/sbd when -s option not provided on init node
2. On join node, ssh to init node, check the status of sbd service, if it's running on init node and have configured on join node, enable sbd service
3. On init node, recording all contents of **class Context** into a file, and on join node fetch that file. So join node will know exactly which option has been specified

What do you think? @arbulu89 @gao-yan

**Comment by arbulu89** [comment]
@liangxin1300 Let's analyze this situation from scratch.
**What do we want?** Configure sbd if `-s` value is given to `crmsh` and add the resource entry in the configuration.
**What do we want is sbd is already configured?** I would expect that crmsh doesn't stop sbd at all, but it only adds the sbd resource to the configuration if `-s` is given.
And, **If `-s` is not provided?** Don't do any operation related to sbd and don't create the sbd resource in the configuration.

Do we agree with this?

At this point, **How the joining node know whether it must enable or not sbd?** It should check if the sbd resource is configured in the 1st node. If this is the case, it should try to start sbd (if it's not started already).

What do you think about this assumptions? When we know what is the behaviour we want, we can discuss about technical/code things.

**Comment by gao-yan** [comment]
> For now I have three ideas:
> 
> 1. Comment out or remove SBD_DEVICE line in sysconfig/sbd when -s option not provided on init node

I think when `init` runs/re-runs, sbd should probably first be reset:

1. Override `/etc/sysconfig/sbd` by copying `/usr/share/fillup-templates/sysconfig.sbd` over

2. Disable `sbd.service`

And sbd fencing resource should be configured only if both `SBD_DEVICE` is configured in `/etc/sysconfig/sbd` and `sbd.service` is enabled.

> 2. On join node, ssh to init node, check the status of sbd service, if it's running on init node and have configured on join node, enable sbd service

Basically the joining node should check if `sbd.service` is enabled on the 1st node and get the consistent. And if `sbd.service` is enabled on the 1st node, get the consistent `/etc/sysconfig/sbd` as well.

> 3. On init node, recording all contents of **class Context** into a file, and on join node fetch that file. So join node will know exactly which option has been specified

Hrm, it'd be a little tricky if it's something to be relied on but somehow got lost/corrupted ... I think the things mentioned above done for `init` and `join` should be good enough to reflect the real situations.

**Comment by liangxin1300** [comment]
@gao-yan @arbulu89 , Thanks for suggestions!
After checking the existing code, personally, I don't want to change a lot for this bug, see PR #579
