### ISSUE TITLE
crm cluster remove NODE_IP should improve the  cleaning up of cluster node

### ISSUE THREAD

**Issue by MalloZup** [ClusterLabs/crmsh#619]
# Description
I found out that I was removing a node with `crm cluster remove IP` left the node in an unclean situation.

I discovered that:

1) the `hacluster` user is still present on the linux machine
2) the `hawk` service is still running.

An already improvement for what we have right now, would be that we print out to the USER what he will need to do manually.
This would be already an improvement to the UX and it has not much dev.

```
... 
Please remove the hacluster user and stop the hawk service
```

I guess something like this could already help.
Open for other suggestion.

I would think that we could even stop hawk service.

Regarding the point 1) , it might be more tricky to handle especially if LInux machines are using AD etc, so I would not do any automation there but just print out to remove the user, so admins known.

**Comment by liangxin1300** [comment]
Thank you @MalloZup for pointing this, I will fire related bug to trace this problem!

**Comment by gao-yan** [comment]
User/group hacluster/haclient are created by cluster-glue package on installation. Since they are not created by `crm cluster init/join`, they shouldn't be removed by `crm cluster remove` either.

**Comment by liangxin1300** [comment]
With #648 merged, I think this issue should be closed
Thanks!
