### ISSUE TITLE
Does corosync3 + pacemaker2 supported by crmsh

### ISSUE THREAD

**Issue by muryliang** [ClusterLabs/crmsh#622]
Hi

I have some problem when using unicast with corosync 2.4.3 + pacemaker 1.1.18 + crmsh 3.0.1,  when join new node into a init cluster with one node, the corosync.conf file can not be updated correctly and will remain with  two_node: 0, exptected_vote: 1.  Only multicast  can correctly update corosync.conf. 
And I learned that Corosync 3 will only support unicast, and I know pcs support Corosync3 + pacemaker2,  I want to know which version of crmsh support Corosync3 + pacemaker2 ?

**Comment by muryliang** [comment]
> Hi @muryliang ,
> crmsh doesn't support corosync3 right now:)

OK. How about the unicast problem I came accross,  should I open another issue or just describe here?

**Comment by liangxin1300** [comment]
> > Hi @muryliang ,
> > crmsh doesn't support corosync3 right now:)
> 
> OK. How about the unicast problem I came accross, should I open another issue or just describe here?

I think this problem has been fixed in latest crmsh-3.0 branch
You can try https://github.com/ClusterLabs/crmsh/releases/tag/3.0.5

**Comment by muryliang** [comment]
> > > Hi @muryliang ,
> > > crmsh doesn't support corosync3 right now:)
> > 
> > 
> > OK. How about the unicast problem I came accross, should I open another issue or just describe here?
> 
> I think this problem has been fixed in latest crmsh-3.0 branch
> You can try https://github.com/ClusterLabs/crmsh/releases/tag/3.0.5

I tried, and it work well in unicast and two_node mode. Thankyou for your help!
