### ISSUE TITLE
we do have underscore on crmsh scripts file

### ISSUE THREAD

**Issue by MalloZup** [ClusterLabs/crmsh#636]
this is an issue we spotted with @gao-yan 

we need to check if we do have other `parameter` which are using `_` score see https://github.com/ClusterLabs/crmsh/pull/635

**Comment by MalloZup** [comment]
@liangxin1300  it might be good if you check if we do have other underscores.

**Comment by liangxin1300** [comment]
Thanks, It looks good to me!
