### ISSUE TITLE
node uname is used as unique id, but it's not

### ISSUE THREAD

**Issue by krig** [ClusterLabs/crmsh#64]
For remote nodes, it is common to have a remote resource named the same as the remote node. In that case, the node uname is the same as the resource id.

However, a common assumption in crmsh is that the node uname can be used as a unique id for the node, which in this case then breaks down.

This is non-trivial to fix since it is a hidden assumption across most of cibconfig.py :/

**Comment by aspiers** [comment]
For reference, see also [bsc#948547 (crmsh complaining coexistence of <node/> and <primitive/> with the same IDs in a pacemaker remote setup.)](https://bugzilla.suse.com/show_bug.cgi?id=948547)
