### ISSUE TITLE
"crm node status" displays XML in newly created cluster

### ISSUE THREAD

**Issue by sjvudp** [ClusterLabs/crmsh#685]
After setting up a new cluster, `crm node status` displayed XML like this:
~~~lang-txt
<nodes>
      <node id="123" UNAME="h23"/>
      ...
</nodes>
~~~
Expected non-XML output.
Version was crmsh-4-2-0+git.1604052559.2a348644-5.26.1 of SLES 15 SP2.

**Comment by liangxin1300** [comment]
Hi @sjvudp ,

`crm node status` show xml, this behavior was by designed(see `crm node help status`), although I personally don't know what is the initial purpose to make this sub-command

You can get the node status by `crm node show` or using `crm_mon` or `crm_node` commands

Thanks!

**Comment by liangxin1300** [comment]
BTW, @sjvudp , what kind of results do you what to get?

**Comment by sjvudp** [comment]
Maybe I actually was confused, but thinking that `crm configure show xml ...` can show the XML of the configuration, couldn't `crm node show xml` do what `crm node status` does?
When using `crm node status` I was just trying out commands, and I was surprised that the default output is XML. I had thought crm shell would avoid (i.e.: hide from the user) XML as much as possible ;-)

**Comment by zzhou1** [comment]
Sounds like to me `crm node status` is unleashed to the end user before the code is finished, or said before the use case get decribed clear enough.

Maybe good to remove it from CLI at the moment?
