### ISSUE TITLE
Multiple " target-role=Stopped"

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#720]
When resource has multiple meta entries, multiple `target-role=Stopped` will be added while stopping the resource:
```
primitive d Dummy \
        meta priority=123 target-role=Stopped \
        meta resource-stickiness=0 allow-migrate=true target-role=Stopped \
        op monitor interval=10s
```
@zzhou1 @gao-yan Do you think this is a bug?

**Comment by zzhou1** [comment]
From the conceptual level, I do read it as a cusmetic issue. I found another cusmetic one as below very recently. No sure if the root cause is same, at least it is similiar.

```
sle15sp2-2:~ # crm config show p_fs
primitive p_fs Filesystem \
        op monitor interval=30s \
        op_params OCF_CHECK_LEVEL=20 \
        params device="/dev/vg1/lv1" directory="/srv/nfs" fstype=xfs
sle15sp2-2:~ # crm resource trace p_fs
INFO: Trace for p_fs is written to /var/lib/heartbeat/trace_ra/
INFO: Trace set, restart p_fs to trace non-monitor operations
sle15sp2-2:~ # crm config show p_fs
primitive p_fs Filesystem \
        op start interval=0 \
        op_params trace_ra=1 \
        op stop interval=0 \
        op_params trace_ra=1 \
        op monitor interval=30s \
        op_params OCF_CHECK_LEVEL=20 trace_ra=1 \
        params device="/dev/vg1/lv1" directory="/srv/nfs" fstype=xfs
sle15sp2-2:~ # crm resource untrace p_fs
sle15sp2-2:~ # crm config show p_fs
primitive p_fs Filesystem \
        op monitor interval=30s \
        op_params OCF_CHECK_LEVEL=20 \
        params device="/dev/vg1/lv1" directory="/srv/nfs" fstype=xfs
```

**Comment by liangxin1300** [comment]
> From the conceptual level, I do read it as a cusmetic issue. I found another cusmetic one as below very recently. No sure if the root cause is same, at least it is similiar.
> 
> ```
> sle15sp2-2:~ # crm config show p_fs
> primitive p_fs Filesystem \
>         op monitor interval=30s \
>         op_params OCF_CHECK_LEVEL=20 \
>         params device="/dev/vg1/lv1" directory="/srv/nfs" fstype=xfs
> sle15sp2-2:~ # crm resource trace p_fs
> INFO: Trace for p_fs is written to /var/lib/heartbeat/trace_ra/
> INFO: Trace set, restart p_fs to trace non-monitor operations
> sle15sp2-2:~ # crm config show p_fs
> primitive p_fs Filesystem \
>         op start interval=0 \
>         op_params trace_ra=1 \
>         op stop interval=0 \
>         op_params trace_ra=1 \
>         op monitor interval=30s \
>         op_params OCF_CHECK_LEVEL=20 trace_ra=1 \
>         params device="/dev/vg1/lv1" directory="/srv/nfs" fstype=xfs
> sle15sp2-2:~ # crm resource untrace p_fs
> sle15sp2-2:~ # crm config show p_fs
> primitive p_fs Filesystem \
>         op monitor interval=30s \
>         op_params OCF_CHECK_LEVEL=20 \
>         params device="/dev/vg1/lv1" directory="/srv/nfs" fstype=xfs
> ```

This is the by design behavior, please see `crm resource help trace`
