### ISSUE TITLE
os.getcwd parameter unused in format (hb_report/utillib.py)

### ISSUE THREAD

**Issue by lge** [ClusterLabs/crmsh#751]
There are a couple "...".format(..., os.getcwd) in utillib where there just is no matching '{}' in the string,
so the os.getcwd is never used and silently dropped.
I suggest to drop it, or add the respective {} at the intended location...
or am I missing sometihng and my python is worse than I thought?

https://github.com/ClusterLabs/crmsh/blob/5d1bf034532d49392cd5e377e3f4f2ab6dccaae6/hb_report/utillib.py#L1524
https://github.com/liangxin1300/crmsh/blob/e8089225801768b4082c5f78fe86539c57ae2f44/hb_report/utillib.py#L1524

**Comment by liangxin1300** [comment]
@lge Thanks for pointing this!
Personally speaking, since we have plan for refactoring hb_report(see https://github.com/ClusterLabs/crmsh/pull/557),
issues like this(maybe wouldn't affect using) doesn't have higher priority.
Anyway, thank you for using crmsh/hb_report!
