### ISSUE TITLE
crm_diff "--no-version" is not properly detected anymore, resulting in "Update was older than existing configuration"

### ISSUE THREAD

**Issue by lge** [ClusterLabs/crmsh#759]
https://github.com/ClusterLabs/crmsh/blob/5d1bf034532d49392cd5e377e3f4f2ab6dccaae6/crmsh/cibconfig.py#L2674

upstream pacemaker moved the output of "--no-version" to "--help-all", it is no longer present in "--help".
result: crm shell uses versioned diffs, which will often fail on a busy cib.

quick fix: use --help-all
(but that would break with pacemaker versions that do not yet know --help-all; which ones would that be?)

```
--- crmsh/cibconfig.py.orig
+++ crmsh/cibconfig.py
@@ -2671,7 +2671,7 @@
 
         # check if crm_diff supports --no-version
         if self._crm_diff_cmd is None:
-            rc, out = utils.get_stdout("crm_diff --help")
+            rc, out = utils.get_stdout("crm_diff --help-all")
             if "--no-version" in out:
                 self._crm_diff_cmd = 'crm_diff --no-version'
             else:
```
 (or just assume that crm_diff supports --no-version, and drop the whole compat detection there, it's been seven years now... pacemaker 1.1.12? .13?)
 
proper, "compatible" fix: instead of parsing help output, actually try to create a diff, in bash I'd do this:
`crm_diff -o <(echo '<cib/>') -n <(echo '<cib/>') --no-version` 
(should give no output and an exit code of 0)

**Comment by liangxin1300** [comment]
Thanks for pointing this!

I think we can drop the whole detection codes here, since I see at least from pacemaker 1.1.6, crm_diff always has `--no-version` option
