### ISSUE TITLE
[Question] Usage for altering operation parameters using crm config set

### ISSUE THREAD

**Issue by asidique** [ClusterLabs/crmsh#826]
Hello,

I'm trying to understand the behaviour for `crm config set` when using it to change a resource's operation parameters. For an example, I have the following resource configuration: 
<pre><code>primitive my_resource my_host \
        params instance=instance1 hostname=host_name \
        op monitor timeout=50s <b>interval=10s</b> on-fail=ignore \
        op start interval=0s timeout=900s \
        op stop interval=0s timeout=900s \
        meta migration-threshold=0 multiple-active=block is-managed=true
</pre></code>

Then, I run `crm config set my_resource.monitor.10s.interval 50s` and it successfully changes the configuration:
<pre><code>primitive my_resource my_host \
        params instance=instance1 hostname=host_name \
        op monitor timeout=50s <b>interval=50s</b> on-fail=ignore \
        op start interval=0s timeout=900s \
        op stop interval=0s timeout=900s \
        meta migration-threshold=0 multiple-active=block is-managed=true
</pre></code>
However, when I want to change the monitor operation again, I'm expecting to use the following command:
`crm config set my_resource.monitor.50s.interval 100s`, however; this results in the following error:
`ERROR: configure.set: Operation "monitor" interval "50s" not found for resource my_resource`. 

Specifying the interval 10s again does work:
`crm config set my_resource.monitor.10s.interval 100s`

Lastly, I know the `crm config set` command doesn't require an interval but I'm interested in understanding the behaviour of the command when using the interval. I tried to also run `crm config commit` and `crm resource refresh` to ensure the configuration is updated but the behaviour is the same.

**Comment by liangxin1300** [comment]
Hi @asidique ,

When first time configured, the `id` for your monitor operation should be `my_resource-monitor-10s`,
After change the interval value as 50s, I think the `id` should update as `my_resource-monitor-50s`, but it not updated
I think this should be a bug.

Thanks for report!
