### ISSUE TITLE
crmsh can't seem to find cluster glue for external devs (vmware)

### ISSUE THREAD

**Issue by mlottgie** [ClusterLabs/crmsh#83]
Trying to configure stonith:external/vmware as follows:

primitive vfencing stonith:external/vcenter \
  params VI_SERVER="vcenter1.example.com" \
    VI_CREDSTORE="/etc/vicredentials.xml" \
  HOSTLIST="cdn1=cdn1.example.com;cdn2=cdn2.example.com;cdn3=cdn3.example.com;cdn4=cdn4.example.com" \
    RESETPOWERON="0" \
    pcmk_host_check="static-list" \
    pcmk_host_list="cdn1;cdn2;cdn3;cdn4" \
  op monitor interval="60"

Upon commit:

stonith:external/vcenter: got no meta-data, does this RA exist?

Checked here:

[root@cdn1 ~]# stonith -L
...
external/vmware
...

stonith -m -t external/vmware <--- output looks like valid xml describing the resource.

and here:
[root@cdn1 ~]# ls -l /usr/lib64/stonith/plugins/external/
...
-rwxr-xr-x 1 root root  5109 Feb 23 12:37 vmware
...

At this time, crm.conf is stock as far as I know:
[path]
sharedir = /usr/share/crmsh
cache = /var/cache/crm
crm_config = /var/lib/pacemaker/cib
crm_daemon_dir = /usr/libexec/pacemaker
crm_daemon_user = hacluster
ocf_root = /usr/lib/ocf
crm_dtd_dir = /usr/share/pacemaker
pe_state_dir = /var/lib/pacemaker/pengine
heartbeat_dir = /var/lib/heartbeat
hb_delnode = /usr/share/heartbeat/hb_delnode
nagios_plugins = /usr/lib64/nagios/plugins

All other items are commented out.

Also:
[root@cdn1 ~]# crm --version
2.1-1.6 (Build unknown)

[root@cdn1 ~]# pacemakerd --version
Pacemaker 1.1.11

Compiled and installed:
cluster-glue-1.0.9-1.el6.x86_64

**Comment by krig** [comment]
Could you run crm -Rd
and attach the output you get when running commit?

**Comment by mlottgie** [comment]
DEBUG: _add_element: append child vfencing to resources
crm(live)configure# commit
.INP: commit
DEBUG: piping string to crm_verify -V -p
.EXT crm_verify -V -p
.EXT crm_resource --show-metadata ocf:heartbeat:Filesystem
DEBUG: ocf:heartbeat:Filesystem: read and cached meta-data
.EXT crm_resource --show-metadata ocf:pacemaker:controld
DEBUG: ocf:pacemaker:controld: read and cached meta-data
.EXT crm_resource --show-metadata stonith:heartbeat:external/vcenter
ERROR: stonith:external/vcenter: got no meta-data, does this RA exist?
.EXT crm_resource --show-metadata stonith:heartbeat:external/vcenter
ERROR: stonith:external/vcenter: got no meta-data, does this RA exist?
ERROR: stonith:external/vcenter: no such resource agent
Do you still want to commit (y/n)?

**Comment by krig** [comment]
Ah, ok. So the problem is that Pacemaker can't find the stonith agents for some reason.
Hrrm, wonder why.

**Comment by krig** [comment]
So yeah, unfortunately it's a problem with Pacemaker which I can't fix here, RHEL doesn't support the glue stonith agents and CentOS uses the same packages.

**Comment by dmuhamedagic** [comment]
On Mon, Feb 23, 2015 at 11:40:59AM -0800, Miles Lott wrote:
> Also:
> [root@cdn1 ~]# crm --version
> 2.1-1.6 (Build unknown)
> 
> [root@cdn1 ~]# pacemakerd --version
> Pacemaker 1.1.11
> 
> Compiled and installed:
> cluster-glue-1.0.9-1.el6.x86_64

This is quite old. The current glue version is 1.0.12. It's
available from

http://download.opensuse.org/repositories/network:/ha-clustering:/Stable

Unfortunately, if pacemaker/crm_resource cannot find stonith
agents that means it wasn't compiled with glue and therefore
cannot use them. That seems to be the case on CentOS/RHEL/Fedora.

If you want to use stonith agents, you'll need to recompile
pacemaker with cluster-glue-libs-devel installed, so that
pacemaker can find stonith header.

You can test for support using "cibadmin -!" and looking for
lha-fencing.
