### ISSUE TITLE
`SBD_DELAY_START=yes` is not enough and also need adjust TimeoutStartSec accordingly

### ISSUE THREAD

**Issue by zzhou1** [ClusterLabs/crmsh#874]
This is the follow up of #842 in regarding to SBD_DELAY_START and sbd systemd TimeoutStartSec

SBD_DELAY_START is used to deal with the situation when the cluster node reboot in the hypervisor environment is too fast. However, set it to yes is not enough. Referring to `man sbd`, the safe value is to let

```
SBD_DELAY_START = token + consensus + pcmk_delay_max + msgwait    # for disk-based 
SBD_DELAY_START = token + consensus + pcmk_delay_max + 2*SBD_WATCHDOG_TIMEOUT    # for disk-less 
```

Meanwhile, it is suggested to adjust sbd systemd TimeoutStartSec to 1.2*SBD_DELAY_START

**Comment by liangxin1300** [comment]
@gao-yan Right now, `pcmk_delay_max` was hard coded in bootstrap.py as `30s`, was it a proper value? And, should we define this `pcmk_delay_max` in `profiles.yam`?

**Comment by gao-yan** [comment]
I think the value is good for most cases. Of course we could also accept any specified value from profile. But if anyhow not set in profile, we probably still should use the recommended value 30s.

**Comment by gao-yan** [comment]
> I think the value is good for most cases. Of course we could also accept any specified value from profile. But if anyhow not set in profile, we probably still should use the recommended value 30s.

Or, if it's somehow unset in profile, we could probably just omit the parameter? Use case I can think of is, clusters with more than 2 nodes do not need the parameter.

**Comment by zzhou1** [comment]
> > I think the value is good for most cases. Of course we could also accept any specified value from profile. But if anyhow not set in profile, we probably still should use the recommended value 30s.
> 

All right. Personally, I prefer to not expose to profiles.yml until end users has need to to play with it explicitly over bootstrap.

> Or, if it's somehow unset in profile, we could probably just omit the parameter? Use case I can think of is, clusters with more than 2 nodes do not need the parameter.

Good point! This is a valid improvement to enable pcmk_delay_* only for 2-node cluster.

**Comment by zzhou1** [comment]
> > Or, if it's somehow unset in profile, we could probably just omit the parameter? Use case I can think of is, clusters with more than 2 nodes do not need the parameter.
> 
> Good point! This is a valid improvement to enable pcmk_delay_* only for 2-node cluster.

BTW, a very little tricky point, `crm cluster join` need enable pcmk_delay_* when it grows to 2-node cluster. Then need disable it when the node number grows to 3 or more.

**Comment by zzhou1** [comment]
Furthermore, stonith-timeout calculation is not enough too in sbd stonith agent. This need crmsh for the more accurate calculation.

**Comment by liangxin1300** [comment]
#890 should already fixed this issue
