### ISSUE TITLE
ERROR in diskless-sbd for `crm cluster init ocfs2 -o /dev/sda`

### ISSUE THREAD

**Issue by zzhou1** [ClusterLabs/crmsh#884]
Unexpected ERROR In 3-node diskless-sbd environment

tw:~ # crm cluster init ocfs2 -o /dev/sda;/dev/sdb -C
INFO: Loading "default" profile from /etc/crm/profiles.yml
INFO: Configuring OCFS2
ERROR: cluster.init: OCFS2 requires stonith device configured and running

**Comment by liangxin1300** [comment]
This is because function `utils.has_stonith_running` return False
`utils.has_stonith_running` calling `stonith_admin -L`, will have different results on 15sp3 and Tumbleweed, under diskless SBD
on 15sp3:
```
0 fence devices found
```
on Tumbleweed:
```
watchdog
1 fence device found
```
