### ISSUE TITLE
Should display complete ocf as `class:provider:type` format, not just show the short type name

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#886]
When configuring ra like:
```
crm configure primitive vip IPaddr2
```
crm configure show will just display the short type name `IPaddr2`
```
# crm configure show

primitive vip IPaddr2 \
```
Should better display complete ocf path as `class:provider:type` format

**Comment by sjvudp** [comment]
For the case cited `crm_mon` actually did display the RA as `ocf:heartbeat:IPaddr2`, but when editing the resource the name was just `IPaddr2` (as initially entered). When attempting to fully qualify the RA, `show changed` in `configure` context did not display anything, and a `commit` was refused, claiming there are no changes to commit. That seems inconsistent.

**Comment by zzhou1** [comment]
I treat this as invalid bug since crmsh does intend to accept and display the RA name only to simplify the user interface back in 2013.

git show 35622767

BTW, I agree "class:provider" is informative to some people, like, developer, advanced user. However, it less useful for the mass majority end users.

**Comment by sjvudp** [comment]
Well, in the past there had been some confusion between two RAs for DRBD being from different providers. When not using a fully qualified RA name, the RA being used may depend on some internal search order. When at some later time one of the RAs is removed, or when the search order is changed, a different RA might be used, possibly causing fatal failures even.
