### ISSUE TITLE
Proper corosync2 split-brain simulation in `crm cluster crash_test`

### ISSUE THREAD

**Issue by zzhou1** [ClusterLabs/crmsh#903]
Some improvement could have for `crm cluster crash_test`

1. more proper corosync2 split-brain simulation would be as below [[REF]]
   iptables -A INPUT ! -i lo -p udp -j DROP && iptables -A OUTPUT ! -o lo -p udp -j DROP

2. it would be even better to help simulate split-brain the cluster node number more than just 2 nodes

[REF]: https://github.com/corosync/corosync/pull/685#issuecomment-972921830

**Comment by liangxin1300** [comment]
#1024
