### ISSUE TITLE
Any cases need to use lock.Lock to avoid race condition?

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#906]
Possible race conditions:
- remove and join
  more complex case: on node1, remove node2, and node3 is joining
- start/stop cluster service and join
- add stage(sbd/qdevice/ocfs2) and join

**Comment by nicholasyang2022** [comment]
It is impossible to implement a perfect locking mechanism in crmsh. Take a complex example: remove _node2_ on _node1_, and join a new _node4_ via _node3_ at the same time. In this case, which node should we place the lock file? There is no trivial answers. It is a problem of bootstrapping: a working distributed lock manager is required to lock probably in a cluster.

And changing cluster topology is not a daily use case. Users should be responsible to avoid race conditions. It is enough for the lock to just cover some most common cases, to prevents some human mistake, for example, run join command concurrently on multiple nodes.
