### ISSUE TITLE
[run-functional-tests] to create tens of nodes expects better performance

### ISSUE THREAD

**Issue by zzhou1** [ClusterLabs/crmsh#962]
I have impression to suggest to move "./autogen.sh && ./configure" outside of the container execution environment. Only need in the host environment, let run-functional-tests prepares it once. It's a waste imaging 10+ of containers to repeat it.

Even further, I'm wondering to deploy all nodes in parallel.

_Originally posted by @zzhou1 in https://github.com/ClusterLabs/crmsh/pull/957#discussion_r847878426_

**Comment by liangxin1300** [comment]
> move "./autogen.sh && ./configure" outside of the container execution environment

This might cause issue, when host os is different with container, like ubuntu vs opensuse, `/usr/bin/python` is not available when doing make
