### ISSUE TITLE
WARNING: crmadmin -S <HOST> unexpected output

### ISSUE THREAD

**Issue by freyes** [ClusterLabs/crmsh#970]
Pacemaker changed the output string of "crmadmin -S <HOST>" in 2.1.0 with the commit https://github.com/ClusterLabs/pacemaker/commit/c26c9951d863e83126f811ee5b91a174fe0cc991 , this is different from the ouput that wait4dc() expects https://github.com/ClusterLabs/crmsh/blob/master/crmsh/utils.py#L898 .

Example output of `crm -w -F node maintenance <HOST>` of a cluster running on Ubuntu 22.04

```
root@juju-0c8f53-zaza-723eab24403d-4:~# crm -w -F node maintenance juju-0c8f53-zaza-723eab24403d-4
WARNING: crmadmin -S juju-0c8f53-zaza-723eab24403d-5 unexpected output: Controller on juju-0c8f53-zaza-723eab24403d-5 in state S_IDLE: ok (exit code: 0)
root@juju-0c8f53-zaza-723eab24403d-4:~# echo $?
1
root@juju-0c8f53-zaza-723eab24403d-4:~# crmadmin -S juju-0c8f53-zaza-723eab24403d-5
Controller on juju-0c8f53-zaza-723eab24403d-5 in state S_IDLE: ok
root@juju-0c8f53-zaza-723eab24403d-4:~# dpkg -l pacemaker crmsh | cat
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version        Architecture Description
+++-==============-==============-============-===========================================
ii  crmsh          4.3.1-1ubuntu2 all          CRM shell for the pacemaker cluster manager
ii  pacemaker      2.1.2-1ubuntu3 amd64        cluster resource manager
```

**Comment by liangxin1300** [comment]
Thanks for pointing this!
I will take a look

**Comment by liangxin1300** [comment]
@freyes The fix for branch crmsh-4.3 is in #972
BTW, I highly suggest to use crmsh 4.4.0 or master branch with pacemaker 2.1+

**Comment by freyes** [comment]
> @freyes The fix for branch crmsh-4.3 is in #972 
Thanks, much appreciated.

>BTW, I highly suggest to use crmsh 4.4.0 or master branch with pacemaker 2.1+
ack

**Comment by heinervdm** [comment]
I'm seeing the same error when using crmsh 4.4.0 with pacemaker 2.1.

**Comment by liangxin1300** [comment]
> I'm seeing the same error when using crmsh 4.4.0 with pacemaker 2.1.

With this https://github.com/ClusterLabs/crmsh/pull/971 got merged in master branch, it should been fixed:)
